Dockerfile
Make it a bit easier to run with a Dockerfile!
=> Add interactive dockerfile

src/P2p/NetNode.cpp
Dumb little spacing issue that's been annoying me on the CLI output.
=> minor spacing issue

src/Transfers/BlockchainSynchronizer.cpp
This might actually be a bug in the code itself...
=> Be explicit about the conditional with misleading/dodgy indentation 

src/SimpleWallet/SimpleWallet.cpp
editor also removed extra whitespaces
=> added confs to SimpleWallet

build-release.sh
Talked with @RocksteadyTC and @nnamon about a script to create releases in a more orderly fashion - this would be my proposal for such a script.
=> Added script to build releases more easily

src/Daemon/Daemon.cpp, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/SimpleWallet.h
Reverts turtlecoin/turtlecoin#65
=> Revert "Wait for input before dying on error"

src/CryptoNoteCore/Account.cpp, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/SimpleWallet.h
We have an incoming_transfers command, and a list_transfers command which shows all transfers, why not an outgoing transfers?
Just had to copy the incoming transfers func and change like one line.
=> Add outgoing transfers command

src/Common/ConsoleHandler.cpp, src/Common/ConsoleHandler.h, src/SimpleWallet/PasswordContainer.cpp, src/SimpleWallet/PasswordContainer.h, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/SimpleWallet.h, src/SimpleWallet/TransferCommand.cpp, src/SimpleWallet/TransferCommand.h
Adds a few things:
* Better startup screen
* Password confirmation on `export_keys`
* Transaction confirmation and password confirmation
* More informative "Wallet file name" input message
=> Simplewallet UI improvements

.gitignore, src/Rpc/RpcServer.cpp, src/Rpc/RpcServer.h
Fixes https://github.com/turtlecoin/turtlecoin/issues/58
=> Add correct content-type and support for cors headers to jsonMethod endpoints

src/SimpleWallet/Transfer.cpp
Sorry, should have caught this before.
=> Add missing newline

src/PaymentGateService/RpcNodeConfiguration.cpp
Thanks to @DiscoTim for spotting.
=> Bytecoind -> Turtlecoind

src/SimpleWallet/Transfer.cpp
Apparently txIsTooLarge() can throw an exception if you don't have enough funds, preventing the sleeping until funds were unlocked to proceed. This moves the sleep before that check, to prevent this issues.
Thanks @soregums!
=> Prevent exception being thrown due to not enough funds

src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/Core.h, src/CryptoNoteCore/CryptoNoteFormatUtils.cpp, src/CryptoNoteCore/CryptoNoteFormatUtils.h, src/Daemon/Daemon.cpp, src/Daemon/DaemonCommandsHandler.cpp, src/Daemon/DaemonCommandsHandler.h, src/Rpc/CoreRpcServerCommandsDefinitions.h, src/Rpc/RpcServer.cpp, src/Rpc/RpcServer.h
1. commit to test if output is correct
Any feedback, tips on improving and suggestions much appreciated.
In final version should solve #85
=> print_bc functionality

src/PaymentGateService/ConfigurationManager.cpp
This should allow any of the walletd parameters to now work from the config file. 
Needs thorough testing of different options.
=> fix config parsing from cmdline/config file for walletd

README.md
Run `./src/TurtleCoind` instead of Run `./src/TurtleCoin`
=> Missing `d`

src/CryptoNoteCore/Checkpoints.cpp
=> Green checkpoints.

src/BinaryInfo/daemon.rc, src/BinaryInfo/miner.rc, src/BinaryInfo/poolwallet.rc, src/BinaryInfo/simplewallet.rc, src/BinaryInfo/walletd.rc
=> Fixes Executable Attributes in Windows

src/SimpleWallet/ParseArguments.cpp, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/Transfer.cpp, src/SimpleWallet/Transfer.h
Also trim whitespaces from transfer command, remove un-needed debug message when using remote node with no port
Fixes https://github.com/turtlecoin/turtlecoin/issues/186
=> Allow cancelling transactions at any time

src/SimpleWallet/SimpleWallet.cpp
Now after 20 seconds we abort the init(). Control flow continues regardless just so the user isn't waiting forever for something to happen, and they can still enter to export their keys or whatever.
=> Fixes a case where a remote node is down and nothing happens

src/SimpleWallet/ParseArguments.h, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/SimpleWallet.h, src/SimpleWallet/Tools.cpp, src/SimpleWallet/Tools.h, src/SimpleWallet/Transfer.cpp, src/SimpleWallet/Transfer.h
Displays payment ID's on incoming/outgoing/list_transfers if one is present.
Handy if you need to pester madk that your deposit hasn't arrived yet :^)
Also removed some unneeded #includes while I was there.
=> Display payment ID's on list_transfers

src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp, src/Daemon/Daemon.cpp
=> Add ascii art on daemon startup and sync

Dockerfile.test, testnet.yml
I wanted to start playing with a testnet, and at @SoreGums direction, updated the build process in the Dockerfile to set a static difficulty of 500.
=> [WIP] Add testnet docker

scripts/makechange.py
Maybe this will be handy for testnets. Spams a ton of transactions to yourself to hopefully make change on the network.
=> Add make change script

scripts/makechange.py
Need to specify different make change address
=> Fixes for sending to a different address

src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/Core.h, src/Daemon/DaemonCommandsHandler.cpp, src/Daemon/DaemonCommandsHandler.h, src/Rpc/CoreRpcServerCommandsDefinitions.h, src/Rpc/RpcServer.cpp, src/Rpc/RpcServer.h
Adds status command to TurtleCoind. In addition, Core now tracks time started.
=> Add status command to TurtleCoind

src/CryptoNoteConfig.h, src/Daemon/DaemonCommandsHandler.cpp, src/Daemon/DaemonCommandsHandler.h, src/Rpc/CoreRpcServerCommandsDefinitions.h, src/Rpc/RpcServer.cpp
Adds hard fork countdown to status command by implementing parameter UPGRADE_HEIGHT_CURRENT. Minor display updates to status sync percentage.
=> Status command updates

src/NodeRpcProxy/NodeRpcProxy.cpp, src/Rpc/RpcServer.cpp
* Adds JSON handlers that mimic the binary handlers in ```RpcServer```
* Changes ```NodeRpcProxy``` to use the new JSON handlers
* Fixes a few typos
=> Start of transition away from binary handlers

include/INode.h, src/Common/FormatTools.cpp, src/Common/FormatTools.h, src/Daemon/DaemonCommandsHandler.cpp, src/Daemon/DaemonCommandsHandler.h, src/InProcessNode/InProcessNode.h, src/NodeRpcProxy/NodeRpcProxy.cpp, src/NodeRpcProxy/NodeRpcProxy.h, src/PaymentGate/NodeFactory.cpp, src/Rpc/CoreRpcServerCommandsDefinitions.h, src/Rpc/RpcServer.cpp, src/Rpc/RpcServer.h, src/SimpleWallet/Commands.cpp, src/SimpleWallet/Commands.h, src/SimpleWallet/SimpleWallet.cpp, tests/UnitTests/INodeStubs.h
Adds the new status command to simplewallet. Consolidates common string functions related to status command to reduce code duplication. Cosmetic updates to fork countdown.
=> Add status command to simplewallet

scripts/makechange.py
On a new network you appear to be able to send to someone else's wallet, but not your own. This fixes the script to support that.
=> Change to work with two wallets instead of one

src/Common/FormatTools.cpp, src/CryptoNoteConfig.h, src/Rpc/CoreRpcServerCommandsDefinitions.h, src/Rpc/RpcServer.cpp
Reverts turtlecoin/turtlecoin#267
=> Revert "Add fork schedule and upgrade notification to status command"

src/CryptoNoteCore/Currency.cpp, src/Wallet/WalletGreen.cpp
=> Fix bug causing optimize to infinite loop

src/CryptoNoteConfig.h, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/Transfer.cpp, src/SimpleWallet/Transfer.h
This time on the right branch.
=> Remove mixin options

src/P2p/NetNode.cpp, src/SimpleWallet/Commands.cpp, src/SimpleWallet/SimpleWallet.cpp, src/SimpleWallet/Sync.cpp, src/SimpleWallet/Sync.h
New feature to save CSV file of wallet transactions in simplewallet
Typo fix to NetNode.cpp ("recognized")
Submitting to development branch, with thanks to Nicholas for help navigating branches! :)
=> New save_csv feature and typo fix

src/CryptoNoteCore/Core.cpp
Also lets us fix the maxMixin overflow bug in a nicer way. Fixes https://github.com/turtlecoin/turtlecoin/issues/287
=> Differentiate between mixin and ring size

src/CryptoNoteCore/RocksDBWrapper.cpp, src/CryptoNoteCore/RocksDBWrapper.h, src/Daemon/Daemon.cpp, src/PaymentGateService/PaymentGateService.cpp
This has been driving me crazy.
=> destoy method

src/CryptoNoteConfig.h, src/CryptoNoteCore/BlockchainCache.cpp, src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/Currency.cpp, src/CryptoNoteCore/Currency.h, src/CryptoNoteCore/DatabaseBlockchainCache.cpp
After weeks of testing and tweaking zawy has arrived on the perfect difficulty algorithm... for now!
This also applies the jagerman MTP patch to make sure we always produce a valid block template. Longer explanation in the code for the effects of this.
=> Hard fork at 600k to use LWMA-2 difficulty algorithm

src/PaymentGate/WalletService.cpp
=> Fix incorrect walletd OOB mixin message

src/ZedWallet/Fusion.cpp, src/ZedWallet/Transfer.cpp
Fixes https://github.com/turtlecoin/turtlecoin/issues/302
Also had to fix some erroneous bracket style :angry:
=> Fix fusion transactions not working with multi-address containers

src/CryptoNoteCore/Currency.cpp
Don't merge yet, had to add a few extra casts to get it to compile and just need to check with zawy it doesn't change the semantics.
=> Prevent divide by zero with 50x attacker (thanks fireice)

src/CryptoNoteCore/Currency.cpp
Add's zawy's latest suggested changes. Still got a decent amount of time to 620k, so should be fine to get all the pools on the latest code.
=> LWMA-2 Tweaks

src/PaymentGateService/PaymentServiceConfiguration.cpp
Accidentally left some debugging information in.
=> Remove unneeded logging

src/ZedWallet/Sync.cpp
As discussed earlier with Z - tidy of amount field + progress bar (shows something is happening as wallets with many transactions can be slow to save).
=> Csv mod - show progress bar for large files + amount tidy up

scripts/checkpointer/delayed-checkpoints.py, scripts/checkpointer/full-checkpoints.py
Credit to @ereptor81 for the original script that was altered.
=> Adding the scripts I use to generate checkpoints

src/zedwallet/CommandImplementations.cpp, src/zedwallet/CommandImplementations.h, src/zedwallet/Sync.cpp, src/zedwallet/Tools.cpp, src/zedwallet/Tools.h
=> FAST timestamps

src/Common/FormatTools.cpp
=> Use period of time rather than amount of blocks for fork notifier

scripts/makechange.py
It now actually sends from both wallets, and grabs the addresses from walletd so you don't have to copy them yourself.
=> Fix makechange

src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
https://chat.turtlecoin.lol -> http://chat.turtlecoin.lol
yay my first pr
=> fix broken link

README.md
Updating directions to always inform new users to build from master.
=> Update Default Build Instructions

CMakeLists.txt
Hoping this won't create an issue on other OS
=> updates cmake to support arm

src/BinaryInfo/service.rc, src/CMakeLists.txt
Try #2 -- now with less conflicts
=> Fixing build targets for rename from walletd to service

src/crypto/slow-hash.c
Saving opcodes in more loops to help speed this bad boy up.
Your mileage may vary.
=> Further slow hash optimizations

src/zedwallet/WalletConfig.h
Walletd has been renamed to service
=> Renamed walletd to service

CMakeLists.txt
Setting a few more flags here that may help with issue #228 
Please let this pass CI tests as this is a web edit and I have not tested on all platforms yet.
=> Update CMakeLists.txt To Address Illegal Instruction

include/INode.h, src/NodeRpcProxy/NodeRpcProxy.cpp, src/NodeRpcProxy/NodeRpcProxy.h, src/PaymentGate/NodeFactory.cpp, src/Rpc/RpcServer.cpp, src/zedwallet/AddressBook.cpp, src/zedwallet/AddressBook.h, src/zedwallet/Commands.cpp, src/zedwallet/Transfer.cpp, src/zedwallet/Transfer.h, src/zedwallet/ZedWallet.cpp, tests/UnitTests/INodeStubs.h
@ZedPea give this a gander, I think I covered it all.
No matter how much I wanted to charge it against fusion transactions -- I didn't. Everything else I think I caught though.
=> [FEATURE] Implementing the use of the node fees in zedwallet

src/BinaryInfo/service.rc, src/Common/FormatTools.cpp, src/PaymentGateService/ConfigurationManager.cpp, src/zedwallet/CommandImplementations.cpp, src/zedwallet/CommandImplementations.h, src/zedwallet/Commands.cpp, src/zedwallet/Sync.cpp, src/zedwallet/WalletConfig.h
Combines bc_height and status into a new status command. This doesn't receive any info directly from the node so it doesn't hang, which was causing some slight issues.
=> Improve status command, remove references to service

src/version.h.in
Afterall, we are breaking a few things.
=> After second thought, let's skip 0.6.4 and go straight to 0.7.0

src/Miner/Miner.cpp, src/Miner/Miner.h, src/Miner/MinerManager.cpp, src/Miner/MinerManager.h
=> Print the current hashrate in the miner every 60s

src/zedwallet/ZedWallet.cpp
just updating the info message to match the available commands with the latest updates
=> replace "bc_height" with "status" as commands have changed

src/zedwallet/CommandImplementations.cpp
=> confirm before resetting wallet

.appveyor.yml
See https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only
It's pretty much either deploy on branch **or** deploy on tag, but not both. So let's just deploy on tag AND add -windows to the filename.
=> [ADMINISTRATIVE] Appveyor, you're almost as bad as Travis

src/WalletService/PaymentServiceJsonRpcServer.cpp
See https://github.com/turtlecoin/turtlecoin-walletd-rpc-php/pull/3
=> [ENHANCEMENT] Adding additional turtle-service method getFeeInfo

src/zedwallet/CommandImplementations.cpp
Fixes https://github.com/turtlecoin/turtlecoin/issues/442
=> [BUGFIX] Fix outgoing transactions overflowing in save_csv

src/CryptoNoteCore/Checkpoints.cpp
Also removes some ugly boost code :smiley: 
It's not a massive performance boost. Before, it took maybe 3 seconds to load the ~750k checkpoints. Now it takes about 1 second.
=> Optimize checkpoint loading

src/zedwallet/AddressBook.cpp, src/zedwallet/CommandImplementations.cpp, src/zedwallet/GetInput.cpp, src/zedwallet/Open.cpp, src/zedwallet/Tools.cpp, src/zedwallet/Tools.h, src/zedwallet/Transfer.cpp
Also made a few functions const because I can't help myself
=> Remove any direct use of boost from zedwallet

src/CryptoNoteCore/Core.cpp
=> [BUGFIX] Fix mixin limits not correctly applying

.appveyor.yml
This follows on the coat tails of https://github.com/turtlecoin/turtlecoin/pull/457
=> [ADMINISTRATIVE] Appveyor Keep Build Artifacts and Push to S3

.travis.yml
=> [ADMINISTRATIVE] Travis Multi-Deployments Fix

src/CryptoNoteConfig.h
***Do not merge this until after the release of 0.8.3*** to avoid all temptation of building 0.8.3 from a commit that includes this. I have opened this PR so we don't forget to do it.
=> [ENHANCEMENT] Activates Legacy Node Blocking

src/Rpc/RpcServer.cpp, src/Rpc/RpcServer.h, src/WalletService/PaymentServiceJsonRpcMessages.cpp, src/WalletService/PaymentServiceJsonRpcMessages.h
Quick clean up in the daemon RPC server and fixing an implicit conversion warning of uint64_t to uint32_t.
=> Tidying up the RPC

src/CryptoNoteConfig.h, src/P2p/NetNode.cpp, src/P2p/P2pNode.cpp
Some people *cough* @zpalmtree make good arguments to support this.
=> [ENHANCEMENT] P2P Version Grace Period Configurable

src/zedwallet/ZedWallet.cpp
I wrote this when I didn't really understand std::future 's (Don't really still, but hey).
We're using a std::async to wait for the result of the std::future, (using another std::future as the result), when we could just use the original std::future, and wait on that.
Btw, easy way to test node timeout, connect to an IP running something, but not a daemon, for example, your router
=> [CLEANUP] Fix double async in node initialization

src/zedwallet/Transfer.cpp
Fixes https://github.com/turtlecoin/turtlecoin/issues/502
=> Reorder the transfer arguments in zedwallet

src/NodeRpcProxy/NodeRpcProxy.cpp
Fixes https://github.com/turtlecoin/turtlecoin/issues/503 I think
=> Fixed a var being uninitialized when turtlecoind is closed

.travis.yml
Not tested, might have got the wrong path
=> Use local fix boost script

src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/Core.h, src/CryptoNoteCore/ITransactionPoolCleaner.h, src/CryptoNoteCore/Mixins.h, src/CryptoNoteCore/TransactionPoolCleaner.cpp, src/CryptoNoteCore/TransactionPoolCleaner.h, src/WalletService/WalletService.cpp
Working towards fixing #492 
Yes... I know this doesn't build as is. And yes, it's because of what I added in `src/CryptoNoteCore/TransactionPoolCleaner.cpp` Line 92.
=> [ENHANCEMENT] Mixin Validation Enhancement & Transaction Pool Cleaner Update

CMakeLists.txt, external/rocksdb/CMakeLists.txt
I **believe** this will resolve #496 
Let's make a mental reminder when we update RocksDB again to not go stomping through the options in its CMakeLists.txt :)
=> [BUGFIX] Adding RocksDB build options back to the build process

include/WalletTypes.h, src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/Core.h, src/Rpc/RpcServer.cpp, src/WalletBackend/SubWallets.cpp, src/WalletBackend/WalletSynchronizer.cpp, src/WalletBackend/WalletSynchronizer.h, src/zedwallet2/ZedWallet2.cpp
=> Add transaction public key on the daemon side

src/BinaryInfo/cryptotest.rc, src/CMakeLists.txt, src/CryptoTest/main.cpp
Kinda does this:
```
cryptotest.exe abcdef7390450324680324860347693874698347639847693874693874602582095378203572035235235234
Input: abcdef7390450324680324860347693874698347639847693874693874602582095378203572035235235234
Cryptonight Fast Hash: 034c8d255b61d1d9244583f984a4e788b0ed62ec015acbe301c58ee6c67a2dd4
Cryptonight v0: 37eb5c97cfabb190daf7c9eb1a803e3a0992997838000675ebf536d1c57beafd
Cryptonight v1: 159683e70afddc865f47eff1f37bbbfd083ba7f9f297f0e54f39368f0147d9fe
Cryptonight Lite v0: 061e2b5ab8b241cd47016adeba9dff0da2692661ac116bd562e591350bb2d8fa
Cryptonight Lite v1: a92298468d234d63aeac2a92a8b21e8d37a286f7f0f514a4a241d6220107a227
```
=> [ENHANCEMENT] Quick Crypto Test Tool for Multi-Hashing

src/Miner/Miner.cpp
For those who are curious as to what's going on in there.
=> Better Miner Reporting

src/Transfers/TransfersConsumer.cpp, src/Transfers/TransfersConsumer.h, src/Transfers/TransfersSynchronizer.cpp, src/Transfers/TransfersSynchronizer.h, src/Wallet/WalletGreen.cpp, src/WalletLegacy/WalletLegacy.cpp
Borrowed from https://github.com/seredat/karbowanec/commit/137f3d9d5693c00e5045a6cd2a25cd42f804c715
Working on testing -- initiating pull for others to test as well.
=> [BUGFIX] Resolving Wallet Coin Burn Bug

src/CryptoTest/main.cpp, src/crypto/hash.h, src/crypto/slow-hash.c, src/crypto/variant2_int_sqrt.h
Adding definitions and underlying changes for
* cn_slow_hash_v2
* cn_lite_slow_hash_v2
Borrowed from https://github.com/monero-project/monero/blob/master/src/crypto/slow-hash.c
=> [ENHANCEMENT] Add Support for CryptoNight Variant 2

src/WalletService/PaymentServiceJsonRpcMessages.cpp, src/WalletService/PaymentServiceJsonRpcServer.cpp, src/WalletService/WalletService.cpp, src/WalletService/WalletService.h
Fixed #547 
If you want to swap view keys (as in swap everything in a container to a new set of keys) create a new container.
=> [BUGFIX] Turtle-Service Reset Method Crashes Wallet

src/config/CryptoNoteConfig.h
=> [BUGFIX] Stops compiling if GENESIS_COINBASE_TX_HEX is empty

src/CryptoTest/main.cpp, src/crypto/hash-ops.h, src/crypto/hash.h, src/crypto/slow-hash.c
I'm pretty sure I finally have this thing under control with this set of changes.
I've also added valid hashes to the cryptotest binary that assert if anything goes sideways.
=> [ENHANCEMENT] Add CN Soft Shell Support

scripts/makechange.py
walletd to turtle-service
less loops
more python, needs python 3.6 now for secrets package
secrets used to get variety in random numbers thx to IBMC
if min is 1 and max is 5000, numbers can actually be 2, 20, 200, 2,000 instead of all being thousands
made things easier for forks by moving params to the top
prints amounts out with messages for easy monitoring
=> Tweaks to makechange.py script

src/CryptoNoteCore/DataBaseConfig.cpp, src/Daemon/DaemonConfiguration.h, src/config/CryptoNoteConfig.h
We weren't using megabytes when loading the default values, so we had a buffer of 256/10 bytes, lol
=> that's a big buffer

.travis.yml, scripts/fix_boost_aarch64.sh
=> Adjusting Travis to use the aarch64 boost script in the main repo

.travis.yml
Opting for GCC-8 for consistency across platforms.
=> One Release Build Per Platform Please

.travis.yml
=> changed copy to cp

src/Common/Util.cpp, src/CryptoNoteCore/Currency.cpp, src/CryptoNoteCore/DataBaseConfig.cpp, src/Daemon/Daemon.cpp, src/Logging/LoggerMessage.cpp, src/Logging/LoggerMessage.h, src/System/TcpStream.cpp, src/System/TcpStream.h
Quite a few bug fixes:
* Fixes premines not working, due to the addresses not being passed through correctly
* Fixes logging not working, due to accidentally removing some overloaded functions
* Fixes the code not correctly checking if the database folder was defaulted due to an uninitialized bool
* Removes some spurious std::cout's
* Fixes create_directories incorrectly returning an error code
=> Premine fix, logging fix

src/CMakeLists.txt, src/Miner/BlockchainMonitor.cpp, src/Miner/BlockchainMonitor.h, src/Miner/Miner.cpp, src/Miner/Miner.h, src/Miner/MinerEvent.h, src/Miner/MinerManager.cpp, src/Miner/MinerManager.h, src/Miner/MiningConfig.cpp, src/Miner/MiningConfig.h, src/Miner/main.cpp
* Command line args no longer mandatory (will prompt for address)
* Lowers scan time to 1 sec to reduce orphans
* Nicer, simpler, coloured output
* Boost no longer needed, bye bye
* Altered the indentation to make reviewing hard
=> Miner usability improvements

src/Errors/ValidateParameters.cpp, src/SubWallets/SubWallet.cpp, src/SubWallets/SubWallet.h, src/SubWallets/SubWallets.cpp, src/SubWallets/SubWallets.h, src/WalletBackend/Transfer.cpp, src/WalletBackend/WalletSynchronizer.cpp, src/WalletBackend/WalletSynchronizer.h
* Fix incorrect mixin message missing bracket
* Fix weird bug where daemon would return different height for same timestamp by converting to height upon receiving block
* Fix transactions segfaulting with 0 mixin
=> Few tweaks

src/CryptoTest/main.cpp
In two separate commits for your reviewing pleasure
I used a few hacks to make the TEST_HASH_FUNCTION easy to use, which are ugly but make the main function nice and clean
=> Cleanup CryptoTest + Performance tests

src/CryptoNoteCore/Core.cpp, src/Errors/Errors.h, src/WalletBackend/Transfer.cpp, src/config/CryptoNoteConfig.h, src/crypto/crypto.cpp, src/crypto/crypto.h
**WARNING: THIS CODE TOUCHES THE CHECK RING SIGNATURE CODE - PLEASE REVIEW CAREFULLY**
=> Verify sigs before sending, cleanup verify sigs API

src/SubWallets/SubWallets.cpp, src/SubWallets/SubWallets.h, src/WalletApi/ApiDispatcher.cpp, src/WalletBackend/WalletBackend.cpp, src/WalletBackend/WalletBackend.h
Makes it easier to backup your private keys.
=> Return privateSpendKey with createAddress

src/Utilities/FormatTools.cpp
=> Fixes #717 fork countdown imprecision

external/cpp-httplib/httplib.h, src/WalletApi/ApiDispatcher.cpp, src/WalletApi/WalletApi.cpp
=> Stop faux socket reuse in httplib and wallet api (#703)

src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/TransactionValidationErrors.h, src/config/CryptoNoteConfig.h, src/config/version.h.in
Resolves #743 
Thanks to @michael-herwig for bringing this to our attention and providing a path for resolution.
=> Blockchain Bloat Exploit Fix

src/WalletApi/ApiDispatcher.cpp, src/WalletApi/ApiDispatcher.h
=> Add a method to validate addresses to wallet-api

src/Miner/BlockchainMonitor.cpp, src/WalletBackend/Transfer.cpp, src/WalletBackend/WalletSynchronizer.cpp
Fixes compilation errors for OSX Clang.
=> macos-travis-fix

src/zedwallet++/CommandImplementations.cpp
=> WIP: Display Incoming Unlock Time in Blocks and Local Time using wallet-api + zedwallet-beta

src/Common/StringTools.cpp, src/Common/StringTools.h, src/Miner/MiningConfig.cpp, src/Miner/MiningConfig.h, src/Utilities/Container.h, src/Utilities/FormatTools.cpp, src/Utilities/FormatTools.h, src/Utilities/Input.cpp, src/Utilities/Input.h, src/Utilities/String.cpp, src/Utilities/String.h, src/Utilities/Utilities.cpp, src/Utilities/Utilities.h, src/zedwallet++/AddressBook.cpp, src/zedwallet++/CommandDispatcher.cpp, src/zedwallet++/CommandImplementations.cpp, src/zedwallet++/Commands.cpp, src/zedwallet++/GetInput.cpp, src/zedwallet++/Open.cpp, src/zedwallet++/ParseArguments.cpp, src/zedwallet++/Transfer.cpp, src/zedwallet++/Utilities.cpp, src/zedwallet++/Utilities.h
* Moving a few things out to the general utilities folder
* Allow https:// or http:// prefix on daemon address
=> Utilities cleanup

src/CryptoNoteCore/BlockValidationErrors.h, src/CryptoNoteCore/Core.cpp, src/Utilities/Container.h, src/Utilities/Utilities.h, src/config/CryptoNoteConfig.h
=> Block Transactions Blob Shuffle

src/SubWallets/SubWallets.cpp
Resolves: #710 
Another JSON mixup!
=> Fix locked transactions getting double added when load from file

src/Common/ShuffleGenerator.h, src/Errors/Errors.cpp, src/Platform/Windows/System/Dispatcher.cpp, src/Platform/Windows/System/Ipv4Resolver.cpp, src/Platform/Windows/System/TcpConnection.cpp, src/Platform/Windows/System/TcpConnector.cpp, src/Platform/Windows/System/TcpListener.cpp
Allows for building in a MSVC 2019 Environment
=> MSVC 2019 Support

src/CryptoNoteCore/Core.cpp, src/CryptoNoteCore/Core.h, src/CryptoNoteCore/ITransactionPool.h, src/CryptoNoteCore/TransactionPool.cpp, src/CryptoNoteCore/TransactionPool.h, src/CryptoNoteCore/TransactionPoolCleaner.cpp, src/CryptoNoteCore/TransactionPoolCleaner.h
And cleans up the code a little bit.
Resolves #767
=> Prioritizes Regular Transactions over Fusion Transactions

src/SubWallets/SubWallets.cpp
=> resolving issue #782

src/Daemon/Daemon.cpp, src/Daemon/DaemonConfiguration.cpp, src/Daemon/DaemonConfiguration.h, src/WalletService/WalletServiceConfiguration.cpp, src/WalletService/WalletServiceConfiguration.h
`--dump-config`, `--save-config`, `--config-file` was tested, no regression.
baby steps for: #714
=> nlohmann -> rapidjson (daemon+wallet config)

src/zedwallet++/AddressBook.cpp, src/zedwallet++/AddressBook.h
`ab_add`, `ab_list`, `ab_delete` was tested, no regression.
baby steps for: #714
=> nlohmann -> rapidjson (zedwallet++)

src/WalletBackend/Transfer.cpp
No idea how I didn't catch this before when it passed all my tests... possibly accidental undo :disappointed:
=> Fix transaction extra encoding bug

CMakeLists.txt, src/CryptoTest/main.cpp
Also fixes a misuse of assert() in cryptotest which made testing confusing :angry:
=> Fix cmake not defaulting to release build

src/zedwallet/CommandImplementations.cpp, src/zedwallet/Transfer.cpp
=> Fix payment ID parsing in zedwallet

src/WalletBackend/BlockDownloader.cpp
Comment pretty much explains it
Maybe also fix an issue causing 'Could not find key image to remove' crash, not sure yet.
=> Fix issue causing excessive fork handling

src/CryptoNoteCore/Currency.cpp, src/CryptoNoteCore/Currency.h, src/CryptoNoteCore/DataBaseConfig.cpp, src/CryptoNoteCore/DataBaseConfig.h, src/CryptoNoteCore/RocksDBWrapper.cpp, src/Daemon/Daemon.cpp, src/Daemon/DaemonConfiguration.cpp, src/P2p/NetNode.cpp, src/P2p/NetNodeConfig.cpp, src/P2p/NetNodeConfig.h, src/P2p/P2pNodeConfig.cpp, src/Rpc/CoreRpcServerCommandsDefinitions.h, src/Rpc/RpcServer.cpp, src/Utilities/FormatTools.cpp, src/config/CryptoNoteConfig.h
* Remove testnet references that have not been supported for some time.
* Remove premine references that have **never** been used during the **entire** life of the project.
=> Remove Legacy Unused Code

src/Miner/BlockUtilities.cpp, src/Miner/BlockUtilities.h
See https://github.com/turtlecoin/turtlecoin/commit/3bf8f7259dda0953d53f8780ec68251cea4449e4#r34313195
@DaveLong Can you see if this fixes your issue? :smiley:
=> Fix issue with miner block serialization

src/subwallets/SubWallet.cpp, src/subwallets/SubWallets.cpp
* Fix potential issue with forked input handling
* Convert consistency crashes to log warnings
=> Backend tweaks

src/cryptonotecore/Core.cpp, src/cryptonotecore/Core.h, src/cryptonotecore/ICore.h, src/cryptonoteprotocol/CryptoNoteProtocolHandler.cpp, src/rpc/CoreRpcServerCommandsDefinitions.h, src/rpc/RpcServer.cpp
=> Bubble the error message from isTransactionValidForPool up to the node RPC call

src/cryptonotecore/Core.cpp
This message can be confusing to some users.
=> Silence peer message

src/common/FileMappedVector.h, src/wallet/WalletGreen.cpp
* Remove `boost::filesystem` in favor of `std::filesystem` in `FileMappedVector.h`
=> Less Boost, More Standard Library

src/daemon/Daemon.cpp
Might as well check all of the port values to be safe.
=> Resolves #889

CMakeLists.txt, src/cryptonotecore/MainChainStorage.cpp, src/daemon/DaemonCommandsHandler.cpp, src/walletservice/WalletService.cpp
Also removes boost regex dependency from `CMakeLists.txt`. Tested the daemon commands on windows and are working perfectly
=> Replacing boost::filesystem and boost::bind with std

src/zedwallet++/Open.cpp
=> Check if file is a directory before attempting to open it

src/daemon/DaemonCommandsHandler.cpp
=> Improve print_pool_sh output

src/daemon/DaemonCommandsHandler.cpp, src/utilities/FormatTools.cpp, src/utilities/FormatTools.h
=> Rework status command

src/daemon/DaemonConfiguration.cpp
=> Resolves #910

src/daemon/DaemonCommandsHandler.cpp
=> Formating of m_consoleHandler.setHandler

src/daemon/DaemonCommandsHandler.cpp
- Add `?` as an alias of `help` in the daemon
- Add the version number to the `status` command in the daemon
=> Improve Daemon Commands A Wee Bit

src/logger/Logger.cpp, src/logger/Logger.h, src/nigel/Nigel.cpp, src/nigel/Nigel.h, src/walletapi/ParseArguments.cpp, src/walletbackend/Transfer.cpp, src/zedwallet++/ParseArguments.cpp
* Log more possible failures in Nigel
* Add TRACE log level
* Log requests and responses
* Return daemon error message from sendtransaction
Resolves: #922 
Resolves: #892 
Only lightly tested, resyncing daemon lol
=> Improved nigel logging

src/cryptonotecore/DatabaseBlockchainCache.cpp
=> Daemon+WalletBackend timestamp adjustments

src/walletapi/ApiDispatcher.cpp
=> Fix a missing public keys to address conversion

include/WalletTypes.h, src/subwallets/SubWallet.cpp, src/subwallets/SubWallet.h, src/subwallets/SubWallets.cpp, src/subwallets/SubWallets.h, src/walletbackend/Transfer.cpp, src/walletbackend/Transfer.h, src/walletbackend/WalletSynchronizer.cpp
=> Don't regenerate key images where not necessary

src/zedwallet++/Transfer.cpp
=> Fix send_all issue where balance < fee+node fee

src/errors/Errors.cpp, src/errors/Errors.h, src/wallet/WalletErrors.h, src/wallet/WalletGreen.cpp, src/walletbackend/Transfer.cpp
Updates WalletBackend and WalletGreen (for `turtle-service`)
=> Make sure that wallets follow the rules set forth in #945

src/config/CryptoNoteConfig.h
Update CuvéeCZ Seed Node due to switching ISP providers (faster, baby!)
=> Update CuvéeCZ Seed Node

src/cryptonotecore/DatabaseBlockchainCache.cpp
Reverts turtlecoin/turtlecoin#933
The DatabaseBlockchainCache is created as a node syncs. As this was previously rounding this to midnight, the only indexes that exist are those that are rounded to midnight. #933 had stopped rounding to midnight and thus is passing the straight timestamp in for reading. Unfortunately, there is no index that matches this position in the past and thus we fail to actually get a response to this call and thus breaks a few of the different RPC calls that rely on `getClosestTimestampBlockIndex()`. While it may not be ideal that the rounding occurs to midnight forcing a resync to rebuild that state data isn't necessarily a good idea either.
=> Revert "Daemon+WalletBackend timestamp adjustments"

src/walletupgrader/Main.cpp
=> Prompt user to add .wallet extension if not present in wallet-upgrader

.github/workflows/matrix.yml
Resolves #966
I also went ahead and removed the requirement that releases are against this repo to make it easier to test changes to the GH releases action on personal repos. Tested that releases are uploaded, tagged, and packaged properly on personal repo as well.
=> Generated artifacts usability improvements

src/noderpcproxy/NodeRpcProxy.cpp, src/rpc/HttpClient.h
=> Add User-Agent Header to HTTP requests made by NodeRpcProxy

src/rpc/RpcServer.cpp
=> Resolved Error in Transaction Input Serialization

external/cpp-httplib/httplib.h
Implements a singular retry in `Client::send()` if the request failed, likely due to a socket timeout issue.
=> HTTP Client Retry on Socket Failure

COMPILE.md, README.md
cleaned up the readme, abstracted the compile instructions
=> readme cleanup

src/cryptonotecore/BlockchainReadBatch.cpp, src/rpc/RpcServer.cpp
=> Fix issue where hash was interpreted as height

src/walletapi/ApiDispatcher.cpp
=> Fix invalidly accessing JSON causing throw

src/subwallets/SubWallet.cpp
Adds sanity checks to prevent accidentally storing the same input in a container more than once.
Potentially fixes #943 , however, is just a band-aid on the actual issue.
=> Ensure we do not add inputs to a container more than once

src/walletapi/ApiDispatcher.cpp, src/walletapi/ApiDispatcher.h, src/walletbackend/WalletBackend.cpp, src/walletbackend/WalletBackend.h
Resolves: #994 
Dumps unencrypted JSON to filepath given.
=> Add exporting wallet JSON to file to wallet-api

src/walletapi/ParseArguments.cpp, src/walletapi/ParseArguments.h, src/walletapi/WalletApi.cpp, src/zedwallet++/ParseArguments.cpp, src/zedwallet++/ParseArguments.h, src/zedwallet++/ZedWallet.cpp
=> Add logging to file arg for zedwallet and wallet-api

src/cryptonotecore/Core.cpp, src/rpc/RpcServer.cpp, src/rpc/RpcServer.h
=> Prevent calling certain endpoints when unsynced

src/walletapi/ApiDispatcher.cpp, src/walletapi/ApiDispatcher.h
=> Add /transactions/paymentid and /transaction/paymentid/{paymentid} endpoints

src/config/CryptoNoteConfig.h, src/crypto/hash.h, src/cryptonotecore/BlockchainCache.cpp, src/cryptonotecore/Core.cpp, src/cryptonotecore/Currency.cpp, src/cryptonotecore/Currency.h, src/cryptonotecore/DatabaseBlockchainCache.cpp, src/cryptotest/main.cpp, src/serialization/CryptoNoteSerialization.cpp
- Major Block v7
- Chukwa v2 (1 thread, 1MB memory, 4 iterations)
- Block 3M activation of v7
- Cryptotest routines added
=> PoW Algorithm Change

src/common/TransactionExtra.cpp, src/common/TransactionExtra.h, src/config/version.h.in, src/cryptonotecore/Currency.cpp
Tested via <https://explorer.turtlecoin.lol/transaction.html?hash=1bfe2e185ada67273438285b00106b002c65468715e708bcf0185123284204ab>
=> Resolves #1083

src/walletbackend/WalletBackend.cpp
=> Update user exposed file path opening with error messages

CMakeLists.txt, src/subwallets/SubWallets.cpp, src/subwallets/SubWallets.h, src/walletbackend/WalletBackend.cpp, src/walletbackend/WalletBackend.h, src/walletbackend/WalletSynchronizer.cpp, src/walletbackend/WalletSynchronizer.h, src/zedwallet++/CommandDispatcher.cpp, src/zedwallet++/CommandImplementations.cpp, src/zedwallet++/CommandImplementations.h, src/zedwallet++/Commands.cpp, src/zedwallet++/Utilities.cpp, src/zedwallet++/Utilities.h
=> added rewind to height option

src/walletapi/ApiDispatcher.cpp, src/walletapi/ApiDispatcher.h, src/walletbackend/WalletBackend.cpp
Added Wallet api rewind endpoint
=> Wallet api rewind

src/subwallets/SubWallets.cpp
=> Prevent importing same wallet multiple times
