- Dockerfile
Log-util service adds its own timestamps to logfiles - turtlecoind already has timestamps, so I changed from using logutil-service to the regular "s6-log", making for easier-to-ready logfiles.
> Dockerfile: switch from logutil-service to standard s6-log

- src/CryptoNoteCore/Checkpoints.cpp
Fixes some users being confused by the green colour and thinking syncing is completed
> Change checkpoint log message colour to yellow

- include/IWalletLegacy.h
- src/CryptoNoteCore/Core.cpp
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- src/Wallet/WalletRpcServer.cpp
- src/Wallet/WalletRpcServer.h
- src/Wallet/WalletRpcServerCommandsDefinitions.h
- src/WalletLegacy/WalletLegacy.cpp
- src/WalletLegacy/WalletLegacy.h
Added the following functionality to the simplewallet:
Ability to restore a wallet from the command line using two new command line parameters, `--restore-spend-key` and `--restore-view-key`.  To be used with `--wallet-file`, this implies the generation of a new wallet.
Added parameter to dump straight out of the wallet after creating it. `--exit-after-generate`.
Added new RPC methods, which are restricted (for security reasons) until `--allow-extended-rpc` is specified which are: `reset`, `stop_wallet`, `get_address`, `view_keys`.
Fixed one bug where wallets would not re-sync from 0, when there was no timestamp known to the requester.
> "Improvements" to simplewallet

- src/PaymentGate/WalletService.cpp
- src/PaymentGate/WalletService.h
- src/PaymentGateService/PaymentGateService.cpp
- src/PaymentGateService/PaymentServiceConfiguration.cpp
- src/PaymentGateService/PaymentServiceConfiguration.h
Add "--view-key" and "--spend-key" arguments to walletd.
- requires "--generate-container" option and is very much dependent that generate-container will self-destruct (which it currently does). I already feel weird if someone posted their keys as a command argument for privacy reasons so if there's a better mechanic here, please advise.
- If these keys are empty, initialize a wallet like it is today; else, try to create the wallet from keys with said keys.
`.\walletd -w test.wallet -p test -g --view-key SECRET_VIEW_KEY --spend-key SECRET_SPEND_KEY`
tips or donations: TRTLuxz9AmQQofRGzM98gf1C9Bix3BraefWK4KcPMEZHZ2MpeaEzrYriMHPRKvBpK9HYyGUcjw4krbmFNrmeiy7E1WiHsRLSLbk
> Add import keys function during generate container

- README.md
- multi_installer.sh
The current easy_installer.sh only supports ubuntu 16+. This PR adds a multi_platform installer with support for OS X and written in an extendible format which can include other OS/distros and be run in a docker container.
> Adding multi_installer.sh for multiplatform installations

- README.md
I fixed up the instructions for building for windows to make them a little easier to read.
I also changed some of the steps, to avoid building the project twice, and to make the project build using multi-threading.
> Fix the windows build instructions

- .gitignore
- src/SimpleWallet/SimpleWallet.cpp
Output private keys on wallet creation and instruct user to save them. Uses stdout so that it's not logged to file.
> Output private keys during new wallet creation

- src/SimpleWallet/SimpleWallet.cpp
Because sometimes I forget Windows exists. Tested on Windows by Serroft.
> ensure color codes show on other non-ansi platforms

- src/CryptoNoteCore/BlockchainCache.cpp
- src/CryptoNoteCore/Core.cpp
The issue is a bit tough to reproduce, but locally I would usually see the error after running the wallet for an hour to an hour and a half. This code has been running on my machine for two and a half hours with no issue. I don't know that I can consider that a proper test, but I figured I should at least get the code out there so that someone who may have been having the issue more consistently can test my fix.
At any rate, I think I made the logic in the function more closely match what the comments said the function should be doing.
I also left in the logging that @MoonMoonDogo had suggested since there was a TODO for it anyway.
#44
> Fix internal node error

- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
Lets you view the outputs of a specific transaction via it's hash, and will print all the outputs that are yours (if any). Useful for ensuring that a specific transaction actually did hit your wallet even if the wallet is playing up.
And here's a picture!
> Add view_tx_outputs command

- src/Daemon/Daemon.cpp
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
Fixes #51 and also applies this to turtlecoind.
Lets the user read the error message if launching from a GUI, but tries to not display it if they launched normally from a terminal, or if they're piping the input or output. I have not managed to test this on windows as I can't seem to get TurtleCoin to compile following the latest instructions.
I believe if it compiles it should work... It should also work on mac, as it looks like mac has the <unistd.h> header.
Hopefully I put all of these in the right places, some simple ones I can confirm it catches is things like having two copies of turtlecoind open (IO Error), and importing a wallet with the same filename as the old one, but if some functions throw exceptions it might not catch all possible errors.
> Wait for input before dying on error

- src/SimpleWallet/PasswordContainer.cpp
- src/SimpleWallet/PasswordContainer.h
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
Added password confirmation prompt in simplewallet when creating a new wallet. Would appreciate someone else giving these a once over w/ all of the different modes of creating/importing wallets, especially on Windows.
> Add password confirmation on new wallets

- .appveyor.yml
- .travis.yml
- README.md
As the title says this enables automated builds for windows, linux, and mac.
Linux and mac are provided by travis - http://travis-ci.org/
Windows is provided by appveyor - https://ci.appveyor.com/
This PR unfortunately requires a bit of interaction on your end - You will have to login via github on both of those websites, and enable builds. I believe on travis it is opt in - you have to flick on the switch to build turtlecoin, whereas I think on appveyor it is enabled for all repositories and you have to disable it for those you don't want it to build for.
Can't say for sure i'm afraid, as I setup travis ages ago and I have a terrible memory even though I setup appveyor a few hours ago.
Then, you can get the fancy icons on the readme to show that the build is succeeding or failing, and a …
> Add CI for windows, linux, and mac

- src/CryptoNoteConfig.h
trival fix for warning: `2018-Mar-17 23:01:05.795769 ERROR   Failed to parse seed address from string: '174.138.68.141'`
> fix seed node missing port to avoid warning on node start

- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
- src/Rpc/RpcServer.h
Example usage:
curl "http://localhost:11898/getpeers"
{"peers":["104.205.164.131:11897","185.134.22.3:11897", ... ]}
> added /getpeers endpoint to return white peer list from daemon

- src/SimpleWallet/ParseArguments.cpp
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- src/SimpleWallet/Transfer.cpp
- src/SimpleWallet/Transfer.h
- src/Wallet/WalletSerializationV1.cpp
If you were upgrading from a legacy wallet, and entered your password incorrectly, then re-entered the password correctly, the spend secret key would be different and hence a different wallet would be imported. This is fixed by just clearing the partially imported wallet when we fail to import.
Thanks to @ereptor81 for finding the issue and helping with debugging.
If you were running the wallet on windows, it would crash upon updating internal cache on another thread. See https://github.com/turtlecoin/turtlecoin/issues/108 for more info. This is now fixed by only doing it on the main thread.
I think this patch is now OK to merge.
> Fix simplewallet not working on windows, incorrectly opening after wrong password entry

- src/SimpleWallet/Tools.cpp
- src/SimpleWallet/Tools.h
- src/SimpleWallet/Transfer.cpp
Makes large balances a bit easier to read.
Before: `Available balance: 3139485.50 TRTL`
After: `Available balance: 3,139,485.50 TRTL`
Unfortunately this doesn't have locale support. Read my long essay in Tools.cpp I wrote for justification on that.
Commas are removed when people are inputting, so you can have a transfer input of `123,456.78` and it will parse fine, for example if the user copy pastes their balance.
> Format money with thousand separators

- src/CryptoNoteConfig.h
- src/SimpleWallet/ParseArguments.cpp
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- src/SimpleWallet/Transfer.cpp
- src/SimpleWallet/Transfer.h
Adds a default mixin of 3 to simplewallet. This is waived if the transaction is dust and cannot be sent without lowering it. This can of course be bypassed by compiling without the restrictions but is a good start to introducing a minimum.
Also fixes issues with being unable to send on testnet.
I couldn't find a way to easily go from a prefix to a string to print out the expected string, so for now it just prints out `TRTL`.
Also fixes windows crashing with "simplewallet.exe has stopped working" when you ctrl+c - it's doing this when exit(0) is called, not sure if this is intended behaviour or possibly something being cleared up calling terminate(), for now it is hacked around :disappointed:  
Also fixes being unable to connect to daemon sometimes on windows - was able to reproduce 100% …
> Default simplewallet mixin, simplewallet bug fixes

- src/CMakeLists.txt
- src/PoolWallet/PasswordContainer.cpp
- src/PoolWallet/PasswordContainer.h
- src/PoolWallet/PoolWallet.cpp
- src/PoolWallet/PoolWallet.h
- src/PoolWallet/TransferCommand.cpp
- src/PoolWallet/TransferCommand.h
- src/SimpleWallet/ParseArguments.cpp
- src/SimpleWallet/ParseArguments.h
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- src/SimpleWallet/Transfer.cpp
Allows easier migration for pools who don't want to upgrade to walletd yet, are using incompatible pools like snipa's, etc.
Adds a deprecation message on startup warning users that this is no longer supported.
> Pool wallet re-upload

- CMakeLists.txt
- build-release.sh
simply add -DDO_TESTS=OFF to cmake.
also updated release script to skip.
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-fassociative-math" -DCMAKE_CXX_FLAGS="-fassociative-math" ../..; time make -j4
real    8m12.852s
user    29m10.744s
sys     2m23.076s
>>>
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-fassociative-math" -DCMAKE_CXX_FLAGS="-fassociative-math" -DDO_TESTS=OFF ../..; time make -j4
real    3m21.756s
user    11m41.880s
sys     1m3.640s
That is a lot faster. Digital Ocean Droplet 4vcpu-8gb.
Also removed connectivity tool from release script
> Building Tests is now optional

- src/SimpleWallet/ParseArguments.cpp
- src/SimpleWallet/ParseArguments.h
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- src/SimpleWallet/Transfer.cpp
Usage: `./simplewallet --wallet-file somefile.wallet --password somesecretpassword`
Also:
* Better output when fusions are being created
* Allow retry when no connection to daemon, or continue regardless, e.g. to export keys
* Use default port when none given with --remote-daemon, e.g. `./simplewallet --remote-daemon public.turtlenode.io`
Be careful about what password you use, as it will be left around in .bash_history
> Add --wallet-file and --password cli arguments

- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.h
- src/CryptoNoteProtocol/ICryptoNoteProtocolQuery.h
- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
- tests/UnitTests/ICryptoNoteProtocolQueryStub.cpp
- tests/UnitTests/ICryptoNoteProtocolQueryStub.h
2018-Apr-04 00:45:45.926279 INFO    TurtleCoin is now syncing to the network height of 325127
> Adds the current blockchain height back to the log messages in the daemon and into the getinfo RPC call

- CMakeLists.txt
- external/CMakeLists.txt
This supplements #136 by @SoreGums as we don't need to build gtests either in the event DO_TESTS is set to off.
> Additional tests can be skipped on build

- src/SimpleWallet/SimpleWallet.cpp
On windows, if the user opens a wallet in one copy of simplewallet, then tries to open the same wallet in another simplewallet, it will crash. This only occurs on windows - on linux you can open the same file multiple times.
This fix just catches the error message and alerts the user to close the other wallets and then retry.
It also includes another fix to add a save command which already got merged because i'm terrible at git..., so just ignore that bit.
> Alert user if wallet already open instead of crashing

- multi_installer.sh
removed the versions from the ubuntu deps as per nnamon suggestion
they aren't needed, tested via digital ocean droplet.
also added -DDO_TESTS=OFF to cut compile time.
if using this script, probably not interested in tests.
closes #50
> update multi_installer.sh fix ubuntu 17.10

- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
* Added the following /getinfo response properties
* synced
* hashrate
* Added /getheight response property
* network_height
```javascript
{
"alt_blocks_count": 0,
"difficulty": 206404553,
"grey_peerlist_size": 1588,
"hashrate": 6880151,
"height": 355175,
"incoming_connections_count": 0,
"last_known_block_index": 355690,
"network_height": 355692,
"outgoing_connections_count": 8,
"status": "OK",
"synced": false,
"tx_count": 319734,
"tx_pool_size": 0,
"white_peerlist_size": 40
}
```
```javascript
{
"alt_blocks_count": 0,
"difficulty": 161661413,
"grey_peerlist_size": 1594,
"hashrate": 5388713,
"height": 355694,
"incoming_connections_count": 0,
"last_known_block_index": 355691,
"network_height": 355694,
"outgoing_connections_count": 8,
"status": "OK",
"synced": true,
"tx_count": 320147, …
```
> Daemon RPC Enhancements

- include/INode.h
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/InProcessNode/InProcessNode.cpp
- src/InProcessNode/InProcessNode.h
- src/NodeRpcProxy/NodeRpcProxy.cpp
- src/NodeRpcProxy/NodeRpcProxy.h
- src/PaymentGate/NodeFactory.cpp
- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
- src/Rpc/RpcServer.h
- src/Serialization/BlockchainExplorerDataSerialization.cpp
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- tests/UnitTests/INodeStubs.cpp
- tests/UnitTests/INodeStubs.h
Caveats:
* It's slower to list all transactions because it has to scour the blockchain
* I had to comment out the serialization of block.penalty due to binary serialization not supporting doubles.
Screenshot:
It should use the users' timezone. It appears to work on GMT, but I haven't tested other time zones.
Both linux and windows work fine - though if TurtleCoind is being slow to respond it will hold up the process quite a bit.
> Add timestamps to simplewallet list_transfers

- src/JsonRpcServer/JsonRpcServer.cpp
These magic numbers are defined in JsonRpc.h, so we might as well use them.
> Use error codes instead of magic numbers

- src/SimpleWallet/SimpleWallet.cpp
This occurs if you open a corrupted wallet, or just some random file.
> Better error message on opening a non wallet file

- README.md
it moved to /scripts, update readme to reflect that.
> fix `multi_installer.sh` path in README.md

- src/SimpleWallet/PasswordContainer.h
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/SimpleWallet.h
- src/SimpleWallet/Tools.cpp
- src/SimpleWallet/Tools.h
- src/SimpleWallet/Transfer.cpp
If we hit an error, go back to the selection screen rather than closing. Gives the user more control, as they can easily exit anyway, with ctrl+c or just closing the window.
Instead of printing out "Could not get timestamp" - just don't print the timestamp.
Small transfer confirmation alteration to sate my ~~autism~~ peculiarities.
> Simplewallet - Return to selection on error, small fixes

- external/rocksdb/CMakeLists.txt
Solves  #171. People with old hardware (pre-Haswell and old AMD CPU's) will have to compile source themselves or download special binaries for older architecture.
> Detect support for AVX/AVX2 in rocksdb

- src/NodeRpcProxy/NodeRpcProxy.cpp
- src/SimpleWallet/SimpleWallet.cpp
It seems if you specified all args needed on the command line, 50% of the time the wallet wouldn't connect to turtlecoind quickly enough, and so would report it is closed. We run the update function in init() once before returning so it is fully inited when it returns.
Also save periodically when scanning chain initially so progress isn't lost if a user exits before it's complete.
> Fix not connecting to remote node initially when all args specified

- src/Rpc/RpcServerConfig.cpp
Adding a description to the command line arguments. Noticed this while working on something else.
> Adding command line description for RPC arguments

- external/CMakeLists.txt
```base
cmake .. -DDO_TESTS=OFF
make -j8
```
```text
real    5m44.033s
user    13m14.948s
sys     0m54.488s
```
```text
real    1m43.796s
user    8m11.024s
sys     0m31.988s
```
Much better. Now my coffee doesn't get cold during the build process.
> RocksDB Build Speedup by allowing the jobServer to operate

- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
> Extends RPC endpoint getinfo to include the current daemon version.

- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/Transfer.cpp
When devving I was using a bigger terminal and didn't realise some of the messages got truncated and looked a bit ugly in a standard windows command prompt.
> Make messages fit better in windows terminal

- src/Rpc/HttpServer.cpp
The long story short here is the the underlying socket encountered a condition where it would throw an exception and the recursive loop would not fire. Thus, when the socket threw the error, the RPC service would stop accepting connections. The NetNode would still be running and sync would be maintained; however, with the RPC server completely unresponsive the daemon appears dead.
This fix, if you will, calls the recursive loop binding before the possibility of the socket throwing the exception thereby allowing the RPC server to continue to accept new connections despite a socket throwing an error.
Pass some love to @yamiM0NSTER as the original way I was attacking this was far more convoluted and his suggestion of moving the bind statement before the socket call is a quick fix.
> BUG FIX: RPC Death on Socket Error

- src/SimpleWallet/SimpleWallet.cpp
Don't think we need to log to a file anymore, haven't found any issues that have needed the log for. Gets kinda big too.
> Remove simplewallet file logger

- src/CryptoNoteConfig.h
- src/CryptoNoteCore/Core.cpp
- src/PaymentGate/WalletService.cpp
- src/SimpleWallet/Transfer.cpp
- src/Wallet/WalletErrors.h
Current limits are 0 - 100. Of course we want to ban 0 mixin later on, but it's not feasible to do without a grace period. This makes transactions out of those limits not get added to the transaction pool. Simplewallet will prevent you from making a transaction outside of those limits, and as will walletd.
Walletd will return a json response like so:
`{'code': -32700, 'data': {'application_code': 32}, 'message': 'Mixin above maximum allowed threshold'}`
> Cap mixin to reasonable levels

- src/CryptoNoteConfig.h
- src/SimpleWallet/Transfer.cpp
- src/Wallet/WalletGreen.cpp
- src/Wallet/WalletGreen.h
After consulting the code I found the correct formula for determining block size, and hence the max size of a transaction that can fit in a block. This is well explained in the comment in WalletGreen.cpp.
It was decided to use the lower bound, so any submitted transaction will always fit in a block, rather than using the theoretical maximum, which could potentially result in a few transactions stuck in the pool.
> Better tx limits

- src/NodeRpcProxy/NodeRpcProxy.cpp
- src/NodeRpcProxy/NodeRpcProxy.h
- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
- src/Rpc/RpcServer.h
The hash one was working, but the one which takes a vector of block heights wasn't implemented. I've found myself wanting this a few times, so I though i'd fill it in.
Still not sure why it returns a vector of vectors, but it would be annoying to change the type as it's inherited in quite a few places in the code base.
> Fill in placeholder method getBlocks

- src/CryptoNoteConfig.h
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/CryptoNoteCore/TransactionValidationErrors.h
- src/PaymentGate/WalletService.cpp
- src/SimpleWallet/Transfer.cpp
To follow up from the previous patch, @SoreGums pointed out that that patch only prevented transactions with mixin out of bounds being included in the pool, but an un-updated/malicious daemon could still include the transaction into a block, which would then cause daemons to crash regardless.
This has tentatively been put at an upgrade height of 450,000. We cannot instantly apply this, as it would prevent new users syncing any previous blocks which fell out of the current mixin bounds. However, this is not hard fork required. Provided no-one submits a block with out of bounds mixin nothing will happen, and if one is, if enough pools are updated then they will just ignore that block.
These bounds have been renamed to be versioned, when mixin bounds change in the future, we can check if the …
> Verify mixin of block transactions

- external/rocksdb/db/c.cc
- external/rocksdb/memtable/inlineskiplist.h
- src/CryptoNoteCore/DatabaseBlockchainCache.cpp
Add a patch from upstream rocksdb to fix gcc8 build: https://github.com/facebook/rocksdb/pull/3736
Adds a missing decrement method needed for boost::iterator_facade: https://www.boost.org/doc/libs/1_67_0/libs/iterator/doc/iterator_facade.html#id24
This is also needed when I checked in boost 1.55, so seems odd it wasn't implemented previously. Perhaps the internal implementation changed and so it is now required.
> Fix build on gcc8

- src/Miner/MiningConfig.cpp
- src/Miner/MiningConfig.h
- src/Miner/main.cpp
- src/PaymentGateService/ConfigurationManager.cpp
- src/PoolWallet/PoolWallet.cpp
After testing different versions of the binaries, wanted to clean up some low hanging fruit...
* Added a new line to the end of the version for walletd and poolwallet.
* Added a command line option to miner to print the version.
> Cleanup the version commands for poolwallet, walletd, and miner.

- src/SimpleWallet/Fusion.cpp
1 minute is often not enough time for funds to unlock.
> Increase fusion balance check timeout

- src/Wallet/WalletGreen.cpp
If a blockIndex of 0 is supplied in error, it will SEGFAULT. As SEGFAULT != FUN let's not do that.
> Resolves SEGFAULT when blockIndex of 0 is requested.

- src/CryptoNoteCore/BlockchainWriteBatch.cpp
Remove "assert(totalTxsCountForPaymentId > 0)" to allow the daemon to run in Debug mode as it does in Release mode.
> remove assert(totalTxsCountForPaymentId > 0)

- src/Platform/Linux/System/Dispatcher.h
Crappy's currently trying to get turtlecoin built on arm64, and ran into an error with a static assert, this fixes that error. It will probably get stuck later on, but every bit helps...
> Fixes one compile failure whilst building on arm64

- src/SimpleWallet/Transfer.cpp
I never see this in normal use so didn't get around to making it fit nicer on a terminal line and cleaning up the messages.
> Slight word changes for split TX messages

- src/CryptoNoteConfig.h
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/CryptoNoteCore/Currency.cpp
- src/CryptoNoteCore/Currency.h
- src/PaymentGate/WalletService.cpp
- src/SimpleWallet/Commands.cpp
- src/SimpleWallet/SimpleWallet.cpp
- src/SimpleWallet/Transfer.cpp
- src/SimpleWallet/Transfer.h
- src/Wallet/WalletGreen.cpp
- tests/UnitTests/TestCurrency.cpp
- tests/UnitTests/TestWallet.cpp
- tests/UnitTests/TransactionApiHelpers.cpp
Fork height is currently set at 600,000, this probably needs to be changed to something to fit with our desired release schedule. 
This fork will set the minimum mixin to 7, and disable dust outputs. This should mean 0 mixin is no longer needed to send dust. The code has been improved to make it easier to implement new mixin forks.
One thing that needs to be tested is what happens to transactions that are currently in the transaction pool when the fork hits, if they have a valid mixin before the fork, but invalid mixin after the fork. ETN experienced this with their recent fork, so blocks were created with these invalid transactions and then rejected.
I would like to test this out on testnet to make sure it's been implemented correctly.
Edit: Currently being tested out on lwma-2 testnet …
> Increase mixin limits and disable dust at next fork

- src/CryptoNoteCore/CryptoNoteSerialization.cpp
- src/Serialization/BinaryInputStreamSerializer.cpp
It's only the mm_tag which can possibly overflow of the 4 tags in the tx_extra, so lets only cap our size if we meet that tag. Occasionally we appeared to need quite large reads to successfully open a wallet.
> Fix wallets losing sync progress

- src/Common/FormatTools.cpp
- src/CryptoNoteConfig.h
- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
* Tells the user if they need to upgrade for the fork or not
* Tells the user if the fork has already happened, and to upgrade if it has and they are not ready.
* Adds an easy mechanism to add new forks and indicate the current softwares fork support: Add a value to FORK_HEIGHTS, and increase the value of CURRENT_FORK_INDEX by one.
E.g: 
```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (next fork in 28.0 days) (Your version of the software is ready for this fork), 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```
or
```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (next fork in 28.0 days) (Your software will need to be upgraded to support this fork), 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```
or
```
Height: 516685/516696 …
```
> Add fork readyness info to status command

- src/PaymentGateService/PaymentGateService.cpp
Instead of using InProcessNode for walletd to talk to the daemon that it's running, this instead launches the RpcServer the same way that the normal daemon does and then uses the NodeRpcProxy to talk the the daemon that is running in its process. While this isn't the most elegant solution, it does appear to resolve #286 
NodeRpcProxy is also uses with the remote daemon when specified -- or when --local is not supplied. So it's basically doing the same thing in 3 out of 3 cases now where it was doing something special for --local that really wasn't the best idea IMO.
***Please have MULTIPLE people test this before it makes it towards release.***
> [BUGFIX] Resolves Walletd Interaction with node via --local flag

- src/SimpleWallet/Sync.cpp
- src/SimpleWallet/Tools.cpp
- src/SimpleWallet/Tools.h
Getting timestamps from the node is very slow, so could possibly slow down syncing, and makes list_transfers et all way slower, so lets just ask the user what they would like. list_transfers is back to taking about a second on my machine now.
> Make timestamps optional in simplewallet

- Dockerfile
- Dockerfile.test
...at least not for docker. This replaces the tagged version with the branch for the docker build, so we won't need to worry about updating the version in the Dockerfile anymore. This also allows us to create a docker image using the development branch by passing a build argument when building (e.g. ```docker build --build-arg TURTLECOIN_BRANCH=development -t turtlecoin .```). The default is set to build the master branch.
> Versions? We don't need no stinking versions!

- src/JsonRpcServer/JsonRpcServer.cpp
- src/PaymentGateService/PaymentServiceConfiguration.cpp
- src/PaymentGateService/PaymentServiceConfiguration.h
Has the same syntax as turtlecoind, e.g. --enable-cors "\*"
(Make sure to quote your "*" otherwise your shell expands it!)
> Add optional cors header to walletd

- src/Mnemonics/electrum-words.cpp
- src/Mnemonics/electrum-words.h
- src/PaymentGate/WalletService.cpp
- src/ZedWallet/Open.cpp
We were just using std::cout to write stuff to the console, but this also should be written to the log file. The logger doesn't inherit from ostream so we're using a template instead, which means the implementation needs to be moved to the header file.
Thanks to @woodyjon for finding this issue.
> Fix mnemonic seed info not being output to walletd log file

- src/Daemon/Daemon.cpp
- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
- src/Rpc/RpcServer.h
Pulled from https://github.com/karai-project/base-client/commit/cd5da0ca0980c548a2dc5d014908e547dfda1168 at the bequest of @RocksteadyTC 
* Command line option added ```--fee-address arg```
* Command line option added ```--fee-amount arg```
Example /feeinfo return:
```javascript
{
"address": "TRTLuxN6FVALYxeAEKhtWDYNS9Vd9dHVp3QHwjKbo76ggQKgUfVjQp8iPypECCy3MwZVyu89k1fWE2Ji6EKedbrqECHHWouZN6g",
"amount": 10,
"status": "OK"
}
```
> Adding /feeinfo JSON HTTP response for specifying a convenience charge remittance information for community nodes.

- src/Rpc/CoreRpcServerCommandsDefinitions.h
This pull request alters critical data payloads between wallets (walletd/zedwallet/poolwallet) and the node (Turtlecoind). 
Previous versions of the wallets will **NOT** work with TurtleCoind as a result of merging this code.
**Wallets (walletd/zedwallet/poolwallet) will need to be of the same release or later from here on out.**
* Removed inner binary serializtion of data in RpcServer for the daemon.
***Please make sure that all testing procedures are completed on ALL platforms before releasing this to the public.***
@RocksteadyTC I have labeled this as a WIP for the time being to keep it from being merged until enough people have tested and signed off on it.
> [WIP] Remove Remaining Binary Handlers From RpcServer

- src/Common/FormatTools.cpp
- src/CryptoNoteConfig.h
- src/CryptoNoteCore/Currency.cpp
- src/Rpc/RpcServer.cpp
- src/zedwallet/CommandImplementations.cpp
Fixes a bug where the wallet would crash when timing out threads (is it RAII or is it not, :roll_eyes:)
Makes FORK_HEIGHTS able to be empty for if people fork our code and don't want any fork info hard coded.
Auto sets current fork index to zero if FORK_HEIGHTS is empty.
Places the genesis_tx_hash in cryptonoteconfig, again for easier forking.
> Bug fixes, tweaks to make us more forkable

- src/zedwallet/AddressBook.cpp
- src/zedwallet/CommandImplementations.cpp
- src/zedwallet/CommandImplementations.h
- src/zedwallet/Commands.cpp
- src/zedwallet/Open.cpp
- src/zedwallet/Tools.cpp
- src/zedwallet/Tools.h
- src/zedwallet/Transfer.cpp
- src/zedwallet/Transfer.h
- src/zedwallet/Types.h
- src/zedwallet/WalletConfig.h
You can now transfer to an integrated address, add them to your address book (and send from your address book), and create them via `make_integrated_address`.
They're a massive 236 characters long!
A new field was added to the address book JSON - so it might wipe your existing address books :thinking: 
Next up - walletd.
> Add integrated addresses to zedwallet

- src/PaymentGate/PaymentServiceJsonRpcMessages.cpp
- src/PaymentGate/PaymentServiceJsonRpcMessages.h
- src/PaymentGate/PaymentServiceJsonRpcServer.cpp
- src/PaymentGate/PaymentServiceJsonRpcServer.h
- src/PaymentGate/WalletService.cpp
- src/PaymentGate/WalletService.h
- src/Wallet/WalletErrors.h
Adds integrated address support to walletd. Adds a new RPC call, createIntegratedAddress(), that takes a parameter `address`, and a parameter `paymentId`, which returns an integrated address created from the two inputs.
This rpc call will need to be added to the relevant RPC libraries and the api-docs updated.
sendTransaction() will now support integrated addresses as arguments, and will correctly convert them to a payment ID and address pair internally.
Suggested usage is sending one transfer, with one integrated address, but if for some reason you want to also specify the payment ID in the json, that will work. If the payment ID in the json and extracted from the integrated address don't match, it will error out. Similarly, if you specify multiple integrated addresses in the transfers …
> Add integrated addresses to walletd

- src/Wallet/WalletGreen.cpp
- src/Wallet/WalletGreen.h
- src/zedwallet/Commands.cpp
- src/zedwallet/Transfer.cpp
- src/zedwallet/Transfer.h
I still need to do a few more sanity checks to check all the edge cases behave as expected, but I think it's good.
I did add a method to walletgreen which lets you get the balance minus dust, which could potentially be helpful for walletd so GUI wallets can implement their send all or better error messages, though with the fork at 620k this probably isn't needed. Let me know if anyone wants it and i'll expose it, could actually add it to getBalance() as another field.
> Adds a send_all command to zedwallet

- src/PaymentGate/WalletService.cpp
- src/zedwallet/CommandImplementations.cpp
- src/zedwallet/Commands.cpp
- src/zedwallet/Tools.cpp
- src/zedwallet/Transfer.cpp
- src/zedwallet/WalletConfig.h
~~Don't merge yet, I don't have a synced wallet to test yet.~~
As katz pointed out, we do some weird encoding where we take the address, add a payment ID to that, and encode it with base58, along with another prefix and checksum which we've already got in the standard address.
Instead, we should just encode the paymentID + two keys, and then add the prefix and checksum to that. This brings integrated address lengths down from 231 chars to 187 chars.
> Rework integrated addresses to be more compact

- src/Rpc/CoreRpcServerCommandsDefinitions.h
This reverts commit 99670d42184600991187f491122730c18d8d6478.
Well.. geez... this is embarrassing.
> Revert "WARNING: Breaking change. removes additional binary serializers from the wallet <-> node communication payloads"

- src/CMakeLists.txt
https://ci.appveyor.com/project/brandonlehmann/turtlecoin/build/1.0.314
This appears to silence the errors about version.h not existing in the AppVeyor CI builds thanks to my shuffling files around a few commits ago.
> [BUGFIX] AppVeyor, why you do me like this?

- .travis.yml
Travis docs say that the build machine has 2 cores — might as well use that to our advantage.
> [ADMINISTRATIVE] Adding jet fuel

- src/WalletService/PaymentServiceJsonRpcMessages.cpp
- src/WalletService/PaymentServiceJsonRpcMessages.h
- src/WalletService/PaymentServiceJsonRpcServer.cpp
- src/WalletService/PaymentServiceJsonRpcServer.h
- src/WalletService/WalletService.cpp
- src/WalletService/WalletService.h
- src/WalletService/main.cpp
This pull exposes the `feeinfo` JSON RPC method for `turtle-service` that relays the information from `/feeinfo` from a daemon.
It also automatically applies the node convenience charges to all transactions sent through `turtle-service` if the node being used specifies one. It does **not** charge this fee on fusion transactions.
Please do not merge without review from others.
> [ENHANCEMENT] Adding node convenience charges to turtle-service

- CMakeLists.txt
Someone wanna give this a go on a Raspberry PI 3 B+?
[turtlecoin-0.7.1rc-arm64.tar.gz](https://github.com/turtlecoin/turtlecoin/files/2304750/turtlecoin-0.7.1rc-arm64.tar.gz)
This was built on my ARM Cortex-A53 w/ Ubuntu Xenial
```
ldd TurtleCoind
linux-vdso.so.1 =>  (0x0000ffff8b7b1000)
libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff8b747000)
libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff8b69a000)
libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8b553000)
/lib/ld-linux-aarch64.so.1 (0x0000ffff8b786000)
```
```
2018-Aug-21 03:46:23.542002 INFO    Block 19800 (0218f8a5369ca2390db3cffb279238dacce2be46750a6472e89ebe8d4b3fa442) added to main chain
2018-Aug-21 03:46:25.262487 INFO    Block 19900 …
```
> [ENHANCEMENT] Flag for aarch64 (aka ARM64) so that it builds

- src/zedwallet/AddressBook.cpp
- src/zedwallet/Transfer.cpp
- src/zedwallet/Transfer.h
Fixes #431
Requires a change to the address book json to store the integrated address rather than the payment ID and address.
> Fix incorrect integrated addresses on the confirm screen

- external/linenoise/linenoise.c
- external/linenoise/linenoise.h
- src/Common/ConsoleHandler.cpp
- fixes a need to double ctrl+c to quit.
- if prompt currently contains a command, ctrl+c will reset the line/cancel the command
- if prompt is empty, ctrl+c raise terminate signal/quit
> Attempt to fix ctrl+c handling (TurtleCoind)

- include/IWallet.h
- src/CryptoNoteConfig.h
- src/Wallet/WalletGreen.cpp
- src/Wallet/WalletGreen.h
- src/Wallet/WalletSerializationV2.cpp
- src/Wallet/WalletSerializationV2.h
- src/WalletService/PaymentGateService.cpp
- src/WalletService/PaymentServiceConfiguration.cpp
- src/WalletService/PaymentServiceConfiguration.h
- src/WalletService/PaymentServiceJsonRpcMessages.cpp
- src/WalletService/PaymentServiceJsonRpcMessages.h
- src/WalletService/PaymentServiceJsonRpcServer.cpp
- src/WalletService/WalletService.cpp
- src/WalletService/WalletService.h
- src/zedwallet/CommandImplementations.cpp
- src/zedwallet/Open.cpp
- src/zedwallet/Open.h
- src/zedwallet/Tools.cpp
- src/zedwallet/Tools.h
- src/zedwallet/ZedWallet.h
Adds support to both turtle-service and zedwallet for starting the wallet scanning at a specific height when importing.
If a wallet is created with no parameters, i.e. it is a completely fresh wallet, not imported, it will always be scanned from the timestamp when it was created. There is no way for it to have any transactions previously, so it is pointless to scan those blocks.
When a wallet is created with parameters, such as a mnemonic seed, a view key, or a view and spend key, an optional scan height can be given. This causes the wallet to ignore any blocks before this point, massively speeding up sync times.
It is worth noting that the block hashes still need to be received from the node. However, this process is far faster than the standard sync process. From my tests I found it …
> [ENHANCEMENT] Allow scanning from a specific height when importing a wallet

- src/crypto/chacha8.h
memcpy() is used to copy around chacha8_keys. For this to be correct, chacha8_key must have a trivial destructor, since the destructor will not be called for the destination of the copy.
This destructor just wipes the data in memory so the key is no longer available, however, this is essentially pointless as WalletService.cpp keeps the password in plaintext in memory.
The main reason for doing this is because on gcc8 it kicks out a ton of these warnings: 
```
In file included from /home/zach/Code/turtlecoin/turtlecoin/src/Wallet/WalletIndices.h:34,
from /home/zach/Code/turtlecoin/turtlecoin/src/Wallet/WalletGreen.h:26,
from /home/zach/Code/turtlecoin/turtlecoin/src/zedwallet/Types.h:11,
from /home/zach/Code/turtlecoin/turtlecoin/src/zedwallet/Transfer.h:9,
from …
```
> [ADMINISTRATIVE] Make chacha8_key trivially copyable

- .travis.yml
- CMakeLists.txt
- scripts/fix_boost_aarch64.sh
The long story short here is that there is no cross-compile ready copies of Boost for AARCH64 in the regular Ubuntu repos. As a result, if we are building for AARCH64 then we need to go download Boost (1.55), set it up in our local folder, link against it, and cross-compile away.
I'll work on adding directions to the main readme on how to Cross compile from Ubuntu
> [ENHANCEMENT] Travis Build AARCH64 Release Binaries

- src/CryptoNoteConfig.h
- src/CryptoNoteCore/Core.cpp
- src/Wallet/WalletUtils.cpp
- src/Wallet/WalletUtils.h
- src/WalletService/PaymentServiceJsonRpcMessages.cpp
- src/WalletService/PaymentServiceJsonRpcMessages.h
- src/WalletService/PaymentServiceJsonRpcServer.h
- src/WalletService/WalletService.cpp
- src/WalletService/WalletService.h
- src/version.h.in
- src/zedwallet/AddressBook.cpp
- src/zedwallet/Commands.cpp
- src/zedwallet/Fusion.cpp
- src/zedwallet/Fusion.h
- src/zedwallet/Transfer.cpp
- src/zedwallet/WalletConfig.h
Sets the mixin to a static 3 at block 800,000.
Makes anonymity an optional parameter in turtle-service. If it is not specified, the DEFAULT_MIXIN_V? will be used where ? is based on the current height.
This means only the turtle-service executable will need updating, and not GUI wallets such as nest, to check for a before/after height to set the anonymity param.
I had to modify the serialization a tad to pass through WalletService, and it does appear to serialize correctly, but I wouldn't mind some extra eyes on this.
TODO: api-docs need updating with both reset from height and this new sendTransaction() modifications. Also might want to modify the pool, and nest.
[I'll fix my fucked up git repo after these PR's are done]
> [ENHANCEMENT] Update mixin to static 3, make anonymity parameter optional in sendTransaction() and friends

- .travis.yml
This will deploy each build to a S3 bucket for quick pull for build testing after Travis does it's thing.
Deploying PRs will come in a later copy.
> [ADMINISTRATIVE] Push all Travis builds to S3 for Core testing

- external/linenoise/linenoise.hpp
- src/zedwallet/ZedWallet.cpp
- src/zedwallet/ZedWallet.h
Added this change - https://github.com/antirez/linenoise/issues/128 - to fix output being funky whilst writing to the terminal and one thread and reading on another.
Call shutdown() when exiting before loading the wallet to provide visual feedback of why `exit` is not instantly exiting.
> [BUGFIX] [ENHANCEMENT] Fix funky output with multithreaded linenoise, and unexpected slow shutdown

- src/Common/FormatTools.cpp
- src/CryptoNoteConfig.h
- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
- src/P2p/NetNode.cpp
- src/P2p/P2pNode.cpp
- src/P2p/P2pProtocolDefinitions.h
This adds new CryptoNoteConfig.h parameters `P2P_CURRENT_VERSION` and `P2P_MINIMUM_VERSION` that have been removed from `P2pProtocolDefinitions.h`
These new parameters are used for simple checks that determine if the incoming/outgoing peers are of a supported P2P network version. As such, it allows us to drop support for older nodes without inadvertently breaking the underlying P2P protocol (by changing it's structure) or forcing a network ID change as other chains have done.
This PR provides a message that is displayed when an old node tries to talk to us (and kills the connection) as well as gives us a warning if we're talking to nodes that are newer than us (keeps the connection active so we can verify an update actually exists while still syncing).
I've also added `LATEST_VERSION_URL` …
> [ENHANCEMENT] Adds the ability to ignore peers that aren't running a supported version

- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
Adds a percentage in the current sync progress prompt and changes behind/ahead the hare to behind/ahead the current peer you're connected to
> Sync prompt edits

- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
- src/P2p/NetNode.cpp
- src/P2p/NetNode.h
- src/P2p/NetNodeCommon.h
In looking into creating a different Transaction Mempool to solve some *observed* issues with the handling of a large influx of Transactions, I found this little tidbit.
As we know, it's possible to send a bunch of transactions (fusion for example) to a node without issue; however, as those transactions are relayed around the network it appears that when our local node is notified of new transactions and they are valid that it will wait to continue processing our event loop until it has notified all of our peers of the transaction. This essentially results in blocking the event loop.
What this PR does is attempts to use the same Transaction relay calls (with a little bit of lipstick) as the daemon RPC sendrawtransaction calls. Thereby pushing the sending of the transactions to our peers …
> [BUGFIX] Incoming Transactions Block The Event Loop

- src/Transfers/BlockchainSynchronizer.cpp
This isn't actually an error that really means anything. We see it a lot in normal operation and it's typically the result of shutting down the service incorrectly more than anything.
Also, if it is a node communication problem, the "Retrying..." message below certainly feels more useful.
> [BUGFIX] Quick Fix for turtle-service "Error"

- src/CryptoNoteConfig.h
- src/WalletService/PaymentServiceConfiguration.cpp
Moved the turtle-service default bind port out into CryptoNoteConfig.h for forkability.
> [ENHANCEMENT] Moving the turtle-service default port to CryptoNoteConfig.h

- src/WalletService/PaymentServiceJsonRpcMessages.cpp
- src/WalletService/PaymentServiceJsonRpcMessages.h
- src/WalletService/PaymentServiceJsonRpcServer.cpp
- src/WalletService/WalletService.cpp
- src/WalletService/WalletService.h
I've tested with a synced node, but when I tried to test with an unsynced node, it was just returning 1. I think it was the daemon playing up though, since zedwallet did the same.
> [ENHANCEMENT] Add daemon local height to wallet getStatus()

- include/INode.h
- src/NodeRpcProxy/NodeRpcProxy.cpp
- src/NodeRpcProxy/NodeRpcProxy.h
- src/WalletService/NodeFactory.cpp
- src/WalletService/PaymentServiceJsonRpcMessages.h
- src/WalletService/WalletService.cpp
- src/WalletService/WalletService.h
@woodyjon reported that `turtle-service` was reporting that the `localDaemonBlockCount` was returning a value of `1` while the daemon was syncing. That kind of defeated the purpose.
As a result, as part of the `/getinfo` call that NodeRpcProxy performs, we'll just snatch the `height` parameter, store it some place, and return that for `localDaemonBlockCount` instead. This gives us results such as the following when we `getStatus` against `turtle-service`.
```javascript
{
"jsonrpc": "2.0",
"result": {
"blockCount": 1,
"knownBlockCount": 795776,
"lastBlockHash": "7fb97df81221dd1366051b2d0bc7f49c66c22ac4431d879c895b06d66ef66f4c",
"localDaemonBlockCount": 14200,
"peerCount": 8
}
}
```
```javascript
{
"jsonrpc": "2.0",
"result": {
"blockCount": 1,
"knownBlockCount": 795783,
"lastBlockHash": …
```
> [BUGFIX] Fix local node height in NodeRpcProxy

- src/CryptoNoteCore/Core.cpp
> [BUGFIX] Core.addBlock() to accept transactions with older mixin values for a period of time.

- src/WalletService/PaymentServiceConfiguration.cpp
- src/WalletService/PaymentServiceConfiguration.h
- src/WalletService/PaymentServiceJsonRpcServer.cpp
We will no longer store the clear text turtle-service password in plain text in memory, in addition, each authentication attempt against the service RPC is passed through the same slow hash function to attempt to slow down brute-force attacks on the password. As it is right now, it's pretty easy to just loop through passwords and pray. This helps slow that down so hopefully someone notices the attempts.
> [ENHANCEMENT] Turtle-Service Brute Force Protection v1

- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
Adds the gray_peers list to the /getpeers RPC API response.
**Old Response:**
```json
{
"peers": ["1.1.1.1", "2.2.2.2"],
"status": "OK"
}
```
**New Response:**
```json
{
"gray_peers": ["3.3.3.3", "4.4.4.4"],
"peers": ["1.1.1.1", "2.2.2.2"],
"status": "OK"
}
```
For compatibility reasons peers has not been renamed to white_peers, but should be something considered in the future.
> Add gray_peers list to RPC GET_PEERS response

- src/zedwallet/CommandImplementations.cpp
- src/zedwallet/Sync.cpp
Also fixes fusion transactions being listed whilst syncing or using incoming_transfers
Fixes https://github.com/turtlecoin/turtlecoin/issues/531
> [BUGFIX] Make a better estimate of view wallet balance

- src/Daemon/DaemonConfiguration.h
implicit_value uses that value unless you do a `=somethingelse` that's not cool. This fixes that so that something like `--load-checkpoints checkpoints.csv` and `--load-checkpoints=checkpoints.csv` works
> [BUGFIX] Daemon would not allow you to specify checkpoints file

- src/WalletService/ConfigurationManager.cpp
- src/WalletService/WalletServiceConfiguration.h
When reading config file as new json format failed, try to read it as old ini format.
keep `--dump-config` and `--save-config` to only use new json format.
```
; file: valid.conf
; this is a valid ini file comment
; this config only includes valid config key
rpc-password=523d4557fe5f9824ae71eaa026c618f41d2cdfd24688978585739e5f337c80ea
container-file=/home/mywallet.twl
container-password=secr3t=-passwUrtz
enable-cors=*
daemon-address=public.turtlenode.io
daemon-port=11898
log-level=0
```
command: `./turtle-service -c valid.conf --dump-config`
output:
```
{
"bind-address": "127.0.0.1",
"bind-port": 8070,
"container-file": "/home/mywallet.twl",
"container-password": "secr3t=-passwUrtz",
"daemon-address": "public.turtlenode.io",
"daemon-port": 11898,
"enable-cors": "*",
"log-file": …
```
> turtle-service: support old flat ini config for backward compatibility

- src/Rpc/HttpServer.cpp
It's not uncommon for poorly implemented RPC clients to not do things how we expect them to do things. This isn't an error on our part and as such we shouldn't warn it that way.
> The HTTP Server is a bit too noisy in the logs

- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/CryptoNoteCore/ICore.h
- src/Rpc/CoreRpcServerCommandsDefinitions.h
- src/Rpc/RpcServer.cpp
- src/Rpc/RpcServer.h
/queryblocks doesn't work like it *should*
/queryblockslite returns partial block information and obscures the coinbase transaction in shortInfo which is a BinaryArray
Enter, /queryblocksdetailed which returns the same data structure as /get_block_details_by_height, /get_blocks_details_by_heights, and /get_blocks_details_by_hashes using the same logic of the last known block
> Adding daemon /queryblocksdetailed

- src/WalletBackend/WalletBackend.cpp
- src/WalletBackend/WalletBackend.h
- src/WalletBackend/WalletSynchronizer.cpp
- src/WalletBackend/WalletSynchronizer.h
- src/zedwallet++/CommandDispatcher.cpp
- src/zedwallet++/CommandImplementations.cpp
- src/zedwallet++/CommandImplementations.h
- src/zedwallet++/Commands.cpp
- src/zedwallet++/GetInput.cpp
- src/zedwallet++/GetInput.h
- src/zedwallet++/Menu.cpp
- src/zedwallet++/ParseArguments.h
- src/zedwallet++/TransactionMonitor.h
- src/zedwallet++/Utilities.cpp
- src/zedwallet++/Utilities.h
- src/zedwallet++/ZedWallet.cpp
* Lets us swap nodes without restarting the program
* Offers this as a command in zedwallet, and if we can't find the daemon on launch
* Fixes std::terminate() being called when an unexpected exception occurs, due to the std::thread's going out of scope without calling .join()
Example:
> Live node swapping, improving handling unexpected exception

- .travis.yml
The GCC build is currently having some toolchain issues causing segfaults. Meanwhile, lets deploy the working clang build.
> Deploy clang OSX build

- src/CryptoNoteCore/BlockchainCache.cpp
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/DatabaseBlockchainCache.cpp
- src/CryptoNoteCore/IBlockchainCache.h
This was causing std::bad_alloc on getGlobalIndexesByRange()
> Fix attempting to retrieve non-existent blocks

- src/WalletService/PaymentGateService.cpp
- src/WalletService/PaymentGateService.h
The logger wasn't correctly initialized when we called currencyBuilder with it. I was under the impression that passing a temporary `shared_ptr` was OK, but it seems not.
We could actually fix this by simply initializing in the header, as I have now done, and changed the order. Initialization of class members is based on their declaration in the file, so the logger would then be defined when the currentBuilder was created, in the initialization list.
However, this form of logic is pretty brittle, and can cause the code to start segfaulting again, just by swapping the order of some variables in the header.
So, I made currency builder a shared_ptr, and initialized it in the constructor body, instead.
> Fix service segfaults caused by initialization order

- src/WalletBackend/SubWallets.cpp
- src/WalletBackend/WalletSynchronizer.cpp
New randomly created addresses weren't being scanned for transactions because we forgot to add the public spend key.
Also need to delete the public spend key when we remove the wallet (not necessary I don't think, but should be done).
And we can grab the spend keys outside the loop - They'll only change in-between scanning of transactions, not midway through.
> Fix new (random) addresses not being scanned

- src/Wallet/WalletGreen.cpp
- src/zedwallet/Transfer.cpp
When trying to send a transaction with money in an address other than the primary, it would report that it is unspendable, due to only gathering the balance minus dust from the main address.
> Fix transfering being semi broken with multiple addresses in one container

- src/WalletApi/ApiDispatcher.cpp
I was doing swagger query parameters wrong (using `[]` instead of `{}`) to indicate parameters that are part of the URL. Once fixed, swagger couldn't figure out that the paths would be different, for example,
`/transactions/{hash}` vs `/transactions/{address}`.
So, just added a small amount to the path to fix any conflicts.
Swagger updates: https://github.com/zpalmtree/wallet-api-docs/commit/2d90804182c08b955e2f4bab3ff3e0457ead1632
Updated site: https://www.futuregadget.xyz/api-docs/
> Slight path tweaks to prevent 'duplicate' swagger paths

- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
With lite blocks, it's expected for this to fail, if a peer doesn't have the transactions yet.
> NOTIFY_MISSING_TXS failure is expected

- external/cpp-httplib/httplib.h
- src/Common/StringTools.cpp
- src/Common/StringTools.h
- src/HTTP/HttpResponse.cpp
- src/Miner/BlockchainMonitor.cpp
- src/Miner/BlockchainMonitor.h
- src/Miner/MinerManager.cpp
- src/Miner/MinerManager.h
- src/Miner/MiningConfig.cpp
- src/Miner/main.cpp
- src/Rpc/HttpClient.cpp
- src/Rpc/HttpClient.h
- src/WalletBackend/SynchronizationStatus.cpp
- src/zedwallet++/AddressBook.cpp
- src/zedwallet++/CommandImplementations.cpp
- src/zedwallet++/GetInput.cpp
- src/zedwallet++/Open.cpp
Easy way to verify that the miner/zedwallet-beta are only using one connection to communicate with the daemon:
```
lsof -i -a -p `pidof miner` -r1
```
If you turn on log level 4 in the daemon, you can also see when a new connection is created. This should occur only once.
This also changes the miner to use cpp-httplib.
> Reuse daemon connections in miner and zedwallet-beta

- .travis.yml
- CMakeLists.txt
- external/cryptopp/CMakeLists.txt
- external/miniupnpc/CMakeLists.txt
- external/rocksdb/CMakeLists.txt
This activates [ccache](https://ccache.samba.org/manual/latest.html) which is a compiler cache system that allows you to cache compiled code on the system. It further adds it to the Travis-CI cache system so that the cache is pulled in on each build. The `cmake` still runs from scratch so if any files are added/removed, they will still be compiled as normal. Only files that remain unchanged will result in a cache hit (and thus go faster).
As a result, the Travis CI build times are significantly reduced once the cache is populated.
**Note:** the initial merge of this PR will result in the ccache being seeded (initial build) and subsequent PRs based on a branch or merges into the branch with the ccache intact will result in **much** faster CI build times.
Proof: …
> Activating ccache in build system

- external/cpp-httplib/httplib.h
Fixes POST without a body timing out and returning a 400 status code
> Assume 0 content length if not specified

- src/WalletApi/WalletApi.cpp
When we were using cpprestsdk it sometimes threw boost errors.
> Remove artifact from when we used a boost httplib

- src/crypto/slow-hash.c
This fixes an error when building in Alpine. musl has a PAGE_SIZE macro defined in limits.h and so it conflicts with the parameter used in slow-hash.c when building.
> Rename PAGE_SIZE parameter

- .appveyor.yml
Found the [clcache](https://github.com/frerich/clcache) package that works kind of like ccache for MSVC.
It builds a compiled object cache and dramatically speeds up build processes once the cache is seeded. I saw builds complete in 50% of the *old* time.
> Make AppVeyor use a compiler cache like Travis-CI does

- src/WalletService/WalletServiceConfiguration.cpp
Re-add the `-l` option for `--log-file` to turtle-service
> turtle-service CLI Parameter

- .travis.yml
- CMakeLists.txt
- README.md
- src/crypto/slow-hash.c
This exposes a few of the preprocessor directives in `slow-hash.c` so that they can be specified easily during the build process via Cmake.
One of the most notable is the FORCE_USE_HEAP (via `-DFORCE_USE_HEAP=1` that is required on CPUs with a smaller L2 cache (ARM). Doing this allows the slow-hash routines to function properly thereby allowing the daemon/node to run on a number of ARM processors.
Special thanks that @thinkpol2 and @LeoStehlik for chasing this issue down and beating it into submission. Both have confirmed proper operation of the daemon on ARM boards. I believe @ExtraHash even has a daemon running on a mobile device in termux 
Resolves #640
> Expose preprocessor definition FORCE_USE_HEAP

- src/Mnemonics/WordList.h
To compile the mnemonics lib before:
```
real	2m0.206s
user	2m1.771s
sys	0m3.910s
```
After:
```
real	0m10.551s
user	0m15.931s
sys	0m2.576s
```
> Speed up mnemonics lib compilation

- src/Transfers/BlockchainSynchronizer.cpp
If switch case UpdateConsumersResult::nothingChanged is triggered while m_node.getKnownBlockCount() != m_node.getLocalBlockCount, switch processing will fall-through to case UpdateConsumersResult::addedNewBlocks.
> Fix fall-through in BlockchainSynchronizer.cpp

- src/WalletBackend/WalletBackend.cpp
- src/WalletBackend/WalletBackend.h
- src/WalletBackend/WalletSynchronizer.cpp
- src/WalletBackend/WalletSynchronizerRAIIWrapper.h
If we called multiple requests at the same time, which needed the wallet synchronizer to be stopped, this could cause join() to be called on the same thread ID multiple times. This threw an exception, which got caught, but returned an internal server error (500), instead of the data requested. Plus, the operation never completes.
This fixes it by adding a RAII wrapper, which locks a mutex, stops the synchronizer, runs the function, and restarts the synchronizer. It is also a lot easier to not accidentally forget to restart the synchronizer.
> Fix data not getting returned by interleaved stop()

- include/WalletTypes.h
- src/SubWallets/SubWallet.cpp
- src/SubWallets/SubWallet.h
- src/SubWallets/SubWallets.cpp
- src/SubWallets/SubWallets.h
- src/WalletBackend/Transfer.cpp
- src/WalletBackend/WalletSynchronizer.cpp
- src/WalletBackend/WalletSynchronizer.h
- src/config/WalletConfig.h
The current model is somewhat overcomplicated by the use of threading. Hopefully this will fix some of the rare crashes.
One thing that this will certainly fix is where we fail to get the required global indexes from the daemon. In short, if a fork happens before we have finished processing the blocks we're aquired from the daemon, the requested global index no longer exists. In the current case, this causes a crash, as I was under the impression it should never happen.
Also, this changes the sync process to support an optional `globalOutputIndex` on the KeyOutput in a block. This ties in to #712 to allow support for getting globalOutputIndexes directly from the daemon.
I don't think we will have a noticeable performance drop with this change.
> Rewrite WalletBackend sync process to be single threaded

- include/WalletTypes.h
> some compilers doesn't like it when non-included library is being used

- .gitignore
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/CryptoNoteCore/ICore.h
- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
- src/CryptoNoteProtocol/CryptoNoteProtocolHandler.h
- src/P2p/ConnectionContext.h
- src/P2p/PendingLiteBlock.h
This is how far I got until a friend shown up that wanna drink with me :). Please have a look and give some feedback.
This should fix all lite block issues except the alternative chain problem as the missing transactions notification still pushes only into the transaction pool and some transactions may still are missing that would be valid on alternative chains.
> lite block fixes

- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/CryptoNoteCore/TransactionValidationErrors.h
- src/Wallet/WalletErrors.h
- src/Wallet/WalletGreen.cpp
- src/config/CryptoNoteConfig.h
Currently capped at 1024 bytes, and fork height set for 1.3 million.
You can easily test by altering the fork height to < current height, and you will see the daemon no longer accepts blocks. Furthermore, you should no longer be able to send transactions in turtle-service with a too large extra.
> Cap the size of tx_extra

- src/NodeRpcProxy/NodeRpcProxy.cpp
- src/NodeRpcProxy/NodeRpcProxy.h
- src/WalletService/NodeFactory.cpp
- src/WalletService/NodeFactory.h
- src/WalletService/PaymentGateService.cpp
- src/WalletService/WalletServiceConfiguration.cpp
- src/WalletService/WalletServiceConfiguration.h
- src/zedwallet/ZedWallet.cpp
add new (optional) `init-timeout` argument+config key. 
Increasing wait time (at runtime) helps with initial connection to remote node in situation where nodes struggle to respond to rpc (when the network fucked-up/etc)
> turtle-service: parameterized init wait timeout

- src/crypto/hash.h
xmr-stak alignment requires that scratchpad is divisible by 64 and division by 64 results in even number
> Algo tweak to Soft-Shell to enable xmr-stak

- CMakeLists.txt
- README.md
- external/cpp-httplib/httplib.h
- src/CMakeLists.txt
- src/Nigel/Nigel.cpp
- src/Nigel/Nigel.h
- src/WalletApi/ApiDispatcher.cpp
- src/WalletApi/ApiDispatcher.h
- src/WalletBackend/WalletBackend.cpp
- src/WalletBackend/WalletBackend.h
- src/zedwallet++/CommandImplementations.cpp
- src/zedwallet++/GetInput.cpp
- src/zedwallet++/GetInput.h
- src/zedwallet++/Menu.cpp
- src/zedwallet++/Open.cpp
- src/zedwallet++/ParseArguments.cpp
- src/zedwallet++/ParseArguments.h
Resolves #713 
Please see the updated build directions on how to enable SSL support. At this time, OpenSSL is linked against as a shared library. As such, I consider it an "advanced user" option as it decreases the portability of the binaries (in my testing at least).
I've done some testing of both zedwallet++ and wallet-api and everything appears to work correctly. Additional testing is appreciated.
The easiest way to enable SSL on a conventional daemon is to pass it through [ngrok](https://ngrok.com/) like so: `ngrok http 11898`
ngrok will then display both http and https (ssl) hostnames and will handle the encryption for you. Just remember that when you're connecting to the ngrok hostname to test SSL that you tell the wallets that the port is `443`.
> WalletBackend (zedwallet++ and wallet-api) support for connecting to SSL daemons

- src/SubWallets/SubWallet.cpp
- src/SubWallets/SubWallet.h
- src/SubWallets/SubWallets.cpp
- src/SubWallets/SubWallets.h
> Massively speed up checking key image owner in WalletBackend

- src/CryptoNoteCore/BlockchainCache.cpp
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/DatabaseBlockchainCache.cpp
- src/config/CryptoNoteConfig.h
> Check transaction input (outputs) unlock times against the last block height @ 1.6M

- include/CryptoNote.h
- include/WalletTypes.h
- src/Nigel/Nigel.cpp
- src/Nigel/Nigel.h
Resolves #712
To test non-ssl, you can sync against: `node.trtlpay.com:80`
To test SSL (when built with SSL), you can sync against: `blockapi.turtlepay.io:443`
**Bonus:** It auto-detects if it's a blockchain cache so a user doesn't have to do anything special
> Support Blockchain cache API in Nigel

- src/Nigel/Nigel.cpp
- src/Nigel/Nigel.h
- src/WalletBackend/WalletSynchronizer.cpp
Implemented a back-off mechanism that cuts the number of blocks requested in half during sync operations if something fails. Once it passes, it moves back up to full power again.
> Wallet Synchronization Back-off Mechanism

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- README.md
- scripts/fix_boost_aarch64.sh
- scripts/prep-aarch64.sh
- src/CMakeLists.txt
* OpenSSL now statically linked during build process
* Turns on checking for OpenSSL during all builds
* If not found, continues to build anyways without SSL features
* Travis & AppVeyor now build with OpenSSL
* Clean up to AARCH64 Travis build process
* Pulled out the preparation steps into a separate script
* Added AARCH64 built dependencies to the Travis-CI cache
* Updated build directions
> Turns on Static OpenSSL Linkage by Default

- src/WalletBackend/WalletSynchronizer.cpp
Allow the daemon/cache to return blocks prior to the one requested as long as the response contains the block we're looking for
> WalletBackend Scan Height Allowance

- src/Daemon/Daemon.cpp
- src/Daemon/DaemonConfiguration.cpp
- src/Daemon/DaemonConfiguration.h
- src/P2p/NetNode.cpp
- src/P2p/NetNode.h
- src/P2p/NetNodeConfig.cpp
- src/P2p/NetNodeConfig.h
able to control clearing p2p state via config.
saves having to figure out a script to remove 
the p2pstate.bin file before starting daemon.
needed for clean container images
> daemon add --p2p-reset-peerstate option

- src/zedwallet++/CommandImplementations.cpp
- src/zedwallet++/Open.cpp
Small cosmetic change that's been bothering me. When creating a wallet, zedwallet++ displays the view key and then the spend key. When restoring a wallet from keys, it asks for the spend key and then the view key. This changes it to request view key and then spend key.
> zedwallet++: ask for spend key first during restore

- CMakeLists.txt
- README.md
- src/crypto/slow-hash.c
The upgrade to Crypto++ 8.x allows us to support building on 32-bit systems.
> enable 32-bit builds

- src/Nigel/Nigel.cpp
Thanks @rashedmyt for discovering.
We call `getNodeFee()` again upon swapping node, but if the address is not valid - for example, if it is empty - then we will not update the node fee results, so the old node fee info will be retained.
> Fix node fee not getting correctly reset upon swapping node

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- README.md
- external/rocksdb/CMakeLists.txt
* Sets the default target architecture to `native` instead of `default`
* Alters CI builds to specify a target architecture of `default`
* Removes tons of RocksDB fluff from the project CMakeLists.txt file and has RocksDB look at the `ARCH` flag instead to determine if it needs to run the feature detection(s)
* Updates the README.md to reflect information regarding the difference between `native` and `default` builds
This PR helps prep the code base for Argon2 optimizations coming in the Chukwa branch that benefit highly from `native` builds.
> Altering default Target Architecture in Build Process

- external/cryptopp/CMakeLists.txt
We don't use the cryptopp shared library and tests so we really should not waste time building them as part of our build processes
> Disable CryptoPP default build parameters that we do not use

- src/Utilities/ThreadSafeDeque.h
- src/Utilities/ThreadSafePriorityQueue.h
- src/WalletApi/ApiDispatcher.cpp
- src/WalletApi/ApiDispatcher.h
- src/WalletApi/ParseArguments.cpp
- src/WalletApi/ParseArguments.h
- src/WalletApi/WalletApi.cpp
- src/WalletBackend/BlockDownloader.cpp
- src/WalletBackend/BlockDownloader.h
- src/WalletBackend/Constants.h
- src/WalletBackend/WalletBackend.cpp
- src/WalletBackend/WalletBackend.h
- src/WalletBackend/WalletSynchronizer.cpp
- src/WalletBackend/WalletSynchronizer.h
- src/zedwallet++/Open.cpp
- src/zedwallet++/ParseArguments.cpp
- src/zedwallet++/ParseArguments.h
Multi-threads the wallet syncing progress. Threads are configurable via command line option.
* ~~I have encountered a couple of rare crashes with `std::bad_alloc`. Have not managed to track down or have a good method to reproduce, hence marked WIP. If anyone is bored and wants to do some performance testing or debugging and could figure out how to reproduce it, that would be grand.~~
* ~~I don't have any performance numbers right now.~~ It was not much faster than with block prefetch when I tested, due to being bottlenecked by the daemon. Planning on looking for some performance improvements there, but do not expect to find many. ~~I also plan on doing a full sync from zero comparison, but the daemon is not playing ball right now.~~
* This should help lower powered devices which are not …
> Multithreaded wallet syncing

- src/config/CryptoNoteConfig.h
Increased DB read & write buffers to 1024 MB, max open files to 500 and 10 DB threads. This is to allow nodes to cope with high volumes of transactions. Helps nodes to stay synced with the network, and / or ensures node to be able to resync as fast as possible. Tested with 66k+ transactions in the pool.
> Increased defaults for DB r/w and # of threads

- src/crypto/slow-hash-arm.c
- src/crypto/slow-hash-common.h
- src/crypto/slow-hash-portable.c
- src/crypto/slow-hash-x86.c
While working on the [turtlecoin-crypto](https://github.com/turtlecoin/turtlecoin-crypto) package, I discovered that the portable slow-hash method was not returning valid hash results. As we seldom build on architectures that aren't x86 or arm (or that don't support AES), this has gone unnoticed for some time.
The easiest way to test for the need for this fix is the following:
To force the use of the portable code, run the following:
```bash
cmake -DNO_AES=1
make -j
./src/cryptotest
```
You will see that the hash test **fails**
Rebuild with AES
```bash
cmake -DNO_AES=0
make -j
./src/cryptotest
```
The hash tests now **pass**
Do the same steps above with this PR pulled in and you'll see that the portable slow-hash now passes the hash tests as expected.
**Note:** I've also moved …
> Fix Portable Slow Hash

- src/CMakeLists.txt
- src/CryptoNoteCore/Core.cpp
- src/CryptoNoteCore/Core.h
- src/Utilities/ParseExtra.cpp
- src/Utilities/ParseExtra.h
- src/config/Constants.h
- src/zedwallet/CommandImplementations.cpp
- src/zedwallet/Tools.cpp
- src/zedwallet/Tools.h
- src/zedwallet/Transfer.cpp
If the payment ID ends with `01`, the public key will be incorrectly parsed, causing transactions to not be scanned correctly. Assuming payment ID's are uniformly distributed, this effects one in every 256 transactions sent with a payment ID.
For example, https://explorer.turtlecoin.lol/transaction.html?hash=13f86f5871526403dd18cc435e0788f254e7e2fd7137c65becf1c09a98a22992 will have the public key parsed as  `01ca1d931715391de63748b4640a2a75faedd53e9da24aee989ca56236ed8921` instead of `ca1d931715391de63748b4640a2a75faedd53e9da24aee989ca56236ed892193`
The bug is in /getwalletsyncdata - so you will need to update your daemon and resync if you are effected by this bug.
The fix takes into account payment ID's and public keys when parsing the extra. I'm not sure if we need to handle any other …
> Fix tx extra public key parsing rare bug

- src/walletapi/ParseArguments.cpp
- src/walletapi/ParseArguments.h
- src/walletapi/WalletApi.cpp
Adds `--no-console` option to wallet-api to allow for sending the process to the background without third-party utilities.
> wallet-api no-console option

- src/walletapi/ApiDispatcher.cpp
All other transaction types return 201, so updating to that.
I don't see any info why setNodeInfo() should return 202 as the request has been accepted and processed, so updating to 200.
Will fix conflicts in a bit, fork is out of date t_t
> Fix a couple of incorrect return codes

- .appveyor.yml
- README.md
now that VS2017 is behind a login - much easier to
use VS 2019 standalone build tools.
> simplify Windows build instructions

- src/cryptonotecore/Currency.cpp
This requires the use of `--rewind-to-height 1799999` on ALL seed nodes and pool nodes.
> Reverts the difficulty reset for the upgrade at 1.8M

- src/walletbackend/WalletBackend.cpp
* Replaced backup mechanism with a simple backup operation (copy the file) before touching anything
* If we can't back up, we exit immediately because moving forward, although unlikely, could result in data loss
* Wallet must be shutdown before attempting to write the new wallet format to the wallet file
> Improved Wallet Upgrade Routine

- src/rpc/CoreRpcServerCommandsDefinitions.h
- src/rpc/RpcServer.cpp
- src/serialization/CryptoNoteSerialization.cpp
Fixes an issue whereby a RawBlock is serialized in the RPC call '/getblocks' that results in the transactions property only containing ONE transaction in the block. This creates the transactions property as an array and loads the transaction information (blob + size) into properties of an object that is added to the array of transactions.
In my code tracing, I was not able to find RawBlock serialization used like this anywhere else in the code other than the RPC call. I have maintained synchronization with the network after these changes, the DB storage all still works, and everything appears operational; however, additional sets of eyes on this and testing would be much appreciated to ensure that I did not miss something.
> Fix RawBlock Serialization

- src/cryptonotecore/Core.cpp
- src/cryptonotecore/ITransactionPool.h
- src/cryptonotecore/TransactionPool.cpp
- src/cryptonotecore/TransactionPool.h
- src/cryptonotecore/TransactionPoolCleaner.cpp
- src/cryptonotecore/TransactionPoolCleaner.h
- Re-order the transaction validation check a bit and short circuit the check if the transaction is already in our mempool
- Remove used transactions from the pool before actualizing the pool on a new block
- add a flush() method to the transaction pool and add it to the Core destructor
There's still plenty of work that can be done to help but this seems to be a decent start.
> Transaction Pool Optimizations

- src/config/CryptoNoteConfig.h
- src/cryptonotecore/Core.cpp
- src/cryptonotecore/TransactionValidationErrors.h
- src/wallet/WalletGreen.cpp
- src/walletbackend/Transfer.cpp
- src/walletbackend/Transfer.h
Offers separate limits for network and client, client limits ensures users do not create outputs that are unspendable, and network limit ensures outputs that are impossible to spend are not created.
> Enforce max output sizes for both client + node

- src/cryptonotecore/Core.cpp
- src/cryptonotecore/Core.h
Replaced the actualizePoolTransactions & actualizePoolTransactionsLite that is used when a new block is added to the TOP of the chain with another method that takes the pre-computed transaction validator state from a new block then uses that state to perform the following:
- Retrieves the full list of transaction hashes from the current pool
- Computes the new maximum transaction size (bytes)
- Loops through the transactions in the pool to identify any that are now invalid with the addition of the new block. The transaction is removed from the transaction pool if one of the following conditions are met:
* If the transaction mixins (ring size) is now invalid
* If the transaction size (bytes) is now too large
* If the transaction contains outputs that were just spent
It skips the following …
> Transaction Pool Validation Improvements on addBlock()

- src/cryptonotecore/Core.cpp
- src/cryptonotecore/Core.h
Small patch on the heels of 904 that helps make sure that the transaction pool is clean during some edge cases. In some edge cases, transactions may be left in the mempool due to a reorg as they aren't caught and cleaned. This adds one extra sanity check that if a transaction in the mempool is found in the chain that we need to clear it from the mempool without doing a deep search.
> Follow up to #904

- CMakeLists.txt
Since boost started shipping cmake config files for all its individual libraries `find_package(Boost)` defaults to those files. We explicitly disable them until boost dependency is removed completely
> Fix boost linking for >= 1.70

- .github/workflows/matrix.yml
The following configurations are enabled for building and testing the code on every push and pull request. Deployment is not yet done (will do it in the near future).
**Configurations**
1. Ubuntu 18.04 - GCC 7.4.0 - boost 1.65.1
2. Ubuntu 18.04 - GCC 8.3.0 - boost 1.65.1
3. Ubuntu 18.04 - Clang 6.0.1 - boost 1.65.1
4. Ubuntu 18.04 - GCC 8.2.1 - boost 1.55.0 (aarch64)
5. Mojave - Clang 8.0.1 - boost 1.71.0
6. Windows - Visual Studio 2019 - boost 1.69.0
Caching is not yet available. All jobs complete within 30 minutes. If you want to have a look at the build, click [here](https://github.com/rashedmyt/turtlecoin/runs/264000170)
> use GitHub Actions for CI/CD

- src/cryptonotecore/MainChainStorage.cpp
Provides a helpful message when data cannot be properly de-serialized from MainChainStorage
> Catch & Re-Throw Deserialization Issues of MainChainStorage

- src/p2p/NetNode.cpp
When trying to debug something, the constant printing of the peer list is very distracting, often taking up thousands of lines. If people require the peer list, they can always use the `print_pl` command, which prints the same info.
> Remove unhelpful peer list logging

- external/argon2/CMakeLists.txt
- external/argon2/arch/x86_64/lib/argon2-ssse3.c
Looks like [SSSE3](https://en.wikipedia.org/wiki/SSSE3) was mistakenly not linked into the Argon2 code. By linking it in, some CPUs may see a performance increase.
> Link in SSSE3 Support in Argon2

- .github/workflows/matrix.yml
- .travis.yml
None of the CI tools are building properly for Catalina and others now that the SDK is all wonky. For now, this insanity needs to stop.
> Mac OSX CI Builds Need To Go

- src/common/Varint.h
- src/config/Constants.h
- src/errors/Errors.cpp
- src/errors/Errors.h
- src/utilities/ParseExtra.cpp
- src/utilities/ParseExtra.h
- src/walletapi/ApiDispatcher.cpp
- src/walletbackend/Transfer.cpp
- src/walletbackend/Transfer.h
- src/walletbackend/WalletBackend.cpp
- src/walletbackend/WalletBackend.h
This allows for the addition of arbitrary hexadecimal data to be added to a transaction nonce via wallet-api.
The additional body parameter `extra` has been added to support this.
Once supplied, the data is encoded behind a special nonce tag (`127`) and appended to the nonce such that:
<tag><varint encoded length of data><data>
Example: https://explorer.turtlecoin.lol/transaction.html?hash=5591fc3bb7384d304341066b214635687c615c860b17024d8cdb593e23aae017
Note: This does not remove the 1,024 byte limit for the TX_EXTRA so that limit still applies.
This matches how I handled this in [turtlecoin-utils](https://github.com/turtlecoin/turtlecoin-utils)
> Allow Arbitrary Data in Transaction Extra Nonce via Wallet-API

- src/zedwallet++/CommandImplementations.cpp
Forgot to update the command to alter log level to handle trace
Also made the descriptions more accurate
> Update zedwallet++ to allow setting trace log level via command

- src/crypto/crypto.cpp
- src/crypto/crypto.h
- src/cryptotest/main.cpp
- src/subwallets/SubWallet.cpp
- src/subwallets/SubWallet.h
- src/subwallets/SubWallets.cpp
- src/subwallets/SubWallets.h
- src/walletapi/ApiDispatcher.cpp
- src/walletapi/ApiDispatcher.h
- src/walletbackend/WalletBackend.cpp
- src/walletbackend/WalletBackend.h
Resolves #831 
- Add new method `Crypto::generate_deterministic_subwallet_keys` that generates new deterministic subwallet keys as defined in #831
- Add walletIndex value to a singular subwallet
- Extend SubWallets to contain the counter used to create subwallets deterministically.
- Switch addSubWallet() to use the new deterministic process
- Add SubWallets::importSubWallet(const uint64_t walletIndex, const uint64_t scanHeight)
- Add WalletBackend::importSubWallet(const uint64_t walletIndex, const uint64_t scanHeight)
- Add new wallet-api endpoint /addresses/import/deterministic
- Requesting /keys/:address: via wallet-api will now return the subwallet index
> Generating deterministic private spend keys for subwallets

- src/config/CryptoNoteConfig.h
- src/cryptonotecore/Core.cpp
- src/cryptonotecore/TransactionValidationErrors.h
- Adds new config parameters: NORMAL_TX_MAX_OUTPUT_RATIO_V1 & NORMAL_TX_MAX_OUTPUT_RATIO_V1_HEIGHT
- NORMAL_TX_MAX_OUTPUT_RATIO_V1: `10`
- NORMAL_TX_MAX_OUTPUT_RATIO_V1_HEIGHT: `2200000`
- The parameters above are used such that a transaction cannot create more than `transactions.inputs.size()` * `NORMAL_TX_MAX_OUTPUT_RATIO` ouputs. This helps to mitigate the decomposition of inputs into hundreds or thousands of outputs that is considered "abnormal" behavior.
- Adds new transaction validation error message describing excessive outputs
- Updates blocktemplate creation routine to NOT select transactions that create an excessive number of outputs when filling the blocktemplate with transactions
- Rejects transactions that fail to follow the above rule from being added to the transaction pool …
> Enforce Excessive Output Creation Limits

- src/cryptonotecore/CachedTransaction.cpp
- src/cryptonotecore/CachedTransaction.h
- src/cryptonotecore/TransactionPool.cpp
This update changes the transaction pool preference ordering such that we now also include the input to output ratio into account when comparing transactions.
- Highest Fee
- Highest aggregate amount transferred
- Highest Input:Output Ratio
- Smaller Transactions
- Older Transactions
Examples:
1) `5` inputs and `35` outputs = `0.142857...`
2) `5` inputs and `20` outputs = `0.25`
3) `25` inputs and `4` outputs = `6.25`
4) `7` inputs and `3500` outputs = `0.002`
5) `80` inputs and `70` outputs = `1.142857...`
The order of which, presuming that all of them have the same fee and aggregate transfer amount would be 3, 5, 2, 1, 4.
> Update Transaction Pool To Account For Additional Metrics in Transaction Ordering

- src/cryptonotecore/DatabaseBlockchainCache.cpp
- src/cryptonotecore/SwappedVector.h
- src/logger/Logger.cpp
- src/logger/Logger.h
blockindexes.bin hold the indexes for each block in the main storage. The file began with 8 bytes with type of uint64_t to represent the count of the entries. After that, for each entry 4 bytes used to store it. The original code will fail the loading if to read fails. But if the indexes file was corrupt due to the incomplete write then the file should be recoverable by updating the count of entries to the correct value.
In this fix, if the EOF comes before the indexes fully loaded, instead of failing it the code will automatically fix it by simply terminate the loop and allow the deamon still working.
> Fix a bug that prevents blockchain to be loaded if the blockindexes.bin corrupts

- .github/workflows/matrix.yml
Using specific versions needs us to update every time there is a bug fix. Since the guys maintaining the [cache](https://github.com/actions/cache) are updating the tag to include these, we don't need specific versions
> use v1 tag to ensure latest bug fixes

- src/cryptonotecore/Core.cpp
- src/cryptonotecore/Core.h
- src/cryptonotecore/TransactionValidationErrors.h
- src/cryptonotecore/ValidateTransaction.cpp
- src/cryptonotecore/ValidateTransaction.h
Pulls transaction validation into a separate file, making it much easier to follow and easier to maintain. 
Needs testing, I have not got around to throwing a ton of invalid transactions at it yet to ensure it works as expected.
> Reorder transaction validation to be easier to follow

- src/cryptonotecore/Core.cpp
- src/cryptonotecore/Core.h
- src/cryptonotecore/ICore.h
- src/cryptonotecore/ValidateTransaction.cpp
- src/cryptonotecore/ValidateTransaction.h
- src/daemon/Daemon.cpp
- src/daemon/DaemonConfiguration.cpp
- src/daemon/DaemonConfiguration.h
- src/utilities/ThreadPool.h
Adds a threadpool which is then utilized to validate the inputs in a transaction in parallel.
Needs a bit more testing. I was seeing some segfaults on my node which I think may be related, running in debug mode to try and track them down now.
This PR is most helpful when
* Syncing from zero *without checkpoints*
* Syncing top blocks which are outside the checkpoints range
I saw my CPU usage go from 8% (1 core out of 12 fully pegged) to between 30-50% usage while syncing without checkpoints.
I think this same idea may be applicable in other parts of the syncing process.
> Threaded input validation

- src/cryptonotecore/ValidateTransaction.cpp
PR #965 enables for multithread validation of inputs but introduces a new security flaw that allow the node to be DDOS-ed.
Possible attack:
An attacker may spam a lot of transactions with a large number of inputs with  the first input is invalid.
Consequences:
The node will perform the validation on all the inputs even one of them is invalid. When this happens in large scale, the node will not be able to perform synchronization for a long time. This effect amplifies on node with slow CPU and disk.
In this fix:
A cancellation flags was added to make the validators to returns immediately if the cancellation is requested due to the invalid inputs. The queue could not be cleared due to the outstanding references of the local stack memory in the lambda expression.
> Cancel the validation if one of the inputs instead wait for all inputs to be fully validated.

- src/cryptonotecore/Core.cpp
To ensure we don't get stuck in a loop where we cannot create blocks because we have a transaction in the pool that was previously valid, but is no longer valid, we should remove invalid transactions from the pool upon failing to add a block containing the tx.
> Remove invalid transactions from pool when included in block

- src/config/CryptoNoteConfig.h
- src/cryptonotecore/TransactionValidationErrors.h
- src/cryptonotecore/ValidateTransaction.cpp
- src/wallet/WalletGreen.cpp
- src/walletbackend/Transfer.cpp
Update output cap to a fixed `30`. May need some discussion. For example, if paying 5 pool users, with an amount of `12345.67`, that's 7 * 5 outputs = 35, and then some change will of course be needed.
> Rework output capping

- src/cryptonotecore/Core.h
- src/nigel/Nigel.cpp
- src/nigel/Nigel.h
Since wallet syncing is generally limited on the speed of fetching data, we can offload some of the daemon's load by letting the client parse the raw blocks, instead. The effect of this will be most apparent when one daemon is serving many different users wallets.
This can also potentially lower the amount of data transferred.
* Should we make it possible to disable this feature using a command line option?
Note: To test this PR, you must be running a daemon with #903 applied.
> Allow syncing with /getrawblocks instead of /getwalletsyncdata

- include/WalletGreenTypes.h
- include/WalletTypes.h
- src/config/CryptoNoteConfig.h
- src/cryptonotecore/ValidateTransaction.cpp
- src/errors/Errors.cpp
- src/errors/Errors.h
- src/errors/ValidateParameters.cpp
- src/errors/ValidateParameters.h
- src/subwallets/SubWallet.cpp
- src/subwallets/SubWallet.h
- src/subwallets/SubWallets.cpp
- src/subwallets/SubWallets.h
- src/utilities/Utilities.cpp
- src/utilities/Utilities.h
- src/wallet/WalletGreen.cpp
- src/wallet/WalletGreen.h
- src/walletapi/ApiDispatcher.cpp
- src/walletapi/ApiDispatcher.h
- src/walletbackend/Transfer.cpp
- src/walletbackend/Transfer.h
- src/walletbackend/WalletBackend.cpp
- src/walletbackend/WalletBackend.h
- src/walletservice/PaymentServiceJsonRpcMessages.cpp
- src/walletservice/PaymentServiceJsonRpcMessages.h
- src/walletservice/PaymentServiceJsonRpcServer.cpp
- src/walletservice/WalletService.cpp
- src/walletservice/WalletService.h
- src/zedwallet++/Transfer.cpp
- src/zedwallet++/Transfer.h
* ~Input ordering for WalletBackend - Suggested method is picking from increasing base10 buckets in order, then wrapping back again to the smallest bucket till amount is fulfilled. This should allow a decent diversity of inputs, while allowing large transactions to be fulfilled and transaction estimates to be relatively accurate.~ Done
* Testing for edge cases
* Testing prepared/delayed transactions
* Updating both `wallet-api` and `turtle-service` documentation to mention `feePerByte` parameter, making `fee` parameter optional for `turtle-service`, updating return type to include the fee of the sent transaction.
* ~Optional: Allow fractional fee per byte to make rounder numbers for fees - since currently they are based on the amount of 256 byte chunks, they don't make for very sexy …
> Fee per byte

- .github/workflows/matrix.yml
The current GH Actions runners do not include the MSVC compiled copies of the OpenSSL libraries nor do they include the MT versions which are required for static linking under MSVC.
This PR downloads and installs the *full* OpenSSL builds similar to those in the README.md which includes the proper libraries and headers via [Chocolatey](https://chocolatey.org/)
> Fixes Issue with GH Actions Built Windows Binaries

- src/daemon/Daemon.cpp
- src/daemon/DaemonCommandsHandler.cpp
- src/daemon/DaemonCommandsHandler.h
Resolve issue whereby the `status` command in the daemon does not always return a result
This is due to binding to a non-interface IP (0.0.0.0) and the fact that we cannot make HTTP calls to 0.0.0.0 reliably and should specify an IP address to issue the RPC calls against. This commit simply replaces 0.0.0.0 with 127.0.0.1 (localhost) for purposes of routing the client RPC request. In addition, creates the http client in the method scope instead of at the class level as I did encounter a few race conditions whereby the commands handler was somehow initializing before the RpcServer instance was able to return the correct port(s).
> Fix Daemon `status` command when using threaded RPC

- src/walletservice/PaymentGateService.cpp
The `--log-level` option should be applied to both the log file and the console.
> Fix turtle-service log levels not working as expected

- src/http/HttpRequest.cpp
- src/http/HttpRequest.h
- src/noderpcproxy/NodeRpcProxy.cpp
- src/noderpcproxy/NodeRpcProxy.h
- src/rpc/HttpClient.h
Threaded RPC requires the use of the proper HTTP method verbs in the requests. This adjusts NodeRpcProxy to use them correctly.
> NodeRpcProxy HTTP Method Fixes

- src/rpc/RpcServer.cpp
This corrects an issue whereby the extra data of a transaction in legacy RPC methods was being improperly encoded after the Threaded RPC was implemented which caused problems with various applications properly syncing the chain from the daemon.
> Fix Legacy RPC Responses Containing Raw TX_EXTRA

- src/cryptonotecore/ValidateTransaction.cpp
- src/cryptonotecore/ValidateTransaction.h
Fix an issue whereby there's a chance that we could try to manipulate the TransactionValidationResult between different threads -- does so by using a mutex to update the validation result instead of directly updating the values
> TransactionValidationResult Cross Thread Safety

- src/rpc/RpcServer.cpp
Resolves #992
Since we switched from:
```c
res.reserved_offset = slow_memmem((void *)block_blob.data(), block_blob.size(), 
&tx_pub_key, sizeof(tx_pub_key));
res.reserved_offset += sizeof(tx_pub_key) + 3;
```
to:
```c
const auto transactionPublicKey = Utilities::getTransactionPublicKeyFromExtra(
blockTemplate.baseTransaction.extra
);
const auto it = std::search(
blockBlob.begin(),
blockBlob.end(),
std::begin(transactionPublicKey.data),
std::end(transactionPublicKey.data)
);
```
This is no longer +3, it's +2 -- because the iterator advanced farther than the previous value
> /getblocktemplate invalid returned offset

- CMakeLists.txt
Helps to resolve an issue if using a different binary such as `cmake3` on some platforms.
> Pass thru cmake used binary to rocksdb cmake build

- src/walletbackend/WalletBackend.cpp
- src/walletbackend/WalletBackend.h
If you repeatedly call /transactions/send/basic or advanced, without waiting for the previous requests to complete, they will use the same inputs most likely, and later requests will all fail. This just adds a mutex to the calls so they execute sequentially.
We may want to consider expanding this (using multiple mutexes) to other non idempotent calls.
> Allow parallel send transaction requests to not interfere with each other

- src/errors/Errors.cpp
- src/errors/Errors.h
- src/errors/ValidateParameters.cpp
- src/errors/ValidateParameters.h
- src/subwallets/SubWallets.cpp
- src/subwallets/SubWallets.h
- src/walletapi/ApiDispatcher.cpp
- src/walletbackend/Transfer.cpp
- src/walletbackend/Transfer.h
- src/walletbackend/WalletBackend.cpp
- src/walletbackend/WalletBackend.h
Adds an `optimizeTarget` parameter to `/transactions/send/fusion/advanced`. Amounts larger than this target will not be fused. Also makes the destination parameter optional.
> Add optimize target parameter

- include/IDataBase.h
- src/cryptonotecore/DatabaseBlockchainCache.cpp
- src/cryptonotecore/RocksDBWrapper.cpp
- src/cryptonotecore/RocksDBWrapper.h
Possible fix to #1022 
Not very tested. Idea is that `Get()` is thread safe whilst `MultiGet` is assumed to not be, so if we just use repeated `Get()`'s, it should be fine to use.
> Use a thread safe DB access method for threaded input is spent check

- src/rpc/RpcServer.cpp
Sometimes, the p2p will report we are synced (due to syncing with someone elses unsynced node). If we check both the height and the p2p sync status, we should get a more accurate result.
Note: Not tested, daemon is syncing.
> Better way to ensure daemon is fully synced

- scripts/prep-aarch64.sh
Hoping the link doesn't break in near future.. we can probably pin it to a specific version using https://www.openssl.org/source/old/1.1.1 links if you are okay with it.
> update openssl to 1.1.1f

- src/daemon/Daemon.cpp
- src/daemon/DaemonConfiguration.cpp
- src/daemon/DaemonConfiguration.h
Changes the daemon configuration option supplied by `--enable-cors` from handling an array, which is not supported in the HTTP header, to a single string for better handling.
This also solves the issue where the `--enable-cors` option was not being saved to configurations and loaded properly.
> Daemon CORS header adjustment

- .github/workflows/matrix.yml
Using specific version of tools in the build command is breaking the builds whenever GitHub is updating their images. Since `clcache` path is automatically added to the path and is before the MSVC compiler, we won't be having any issues by not specifying the CLToolPath switch. Have confirmed caching works as expected.
Also
* updated the yaml file to use the latest version of images and actions.
* Removed openssl installation on windows since it is provided in many versions by windows image
> [ci/cd] Update matrix.yml

- src/transfers/TransfersConsumer.cpp
If the final transaction in a block has an invalid public key, the transaction will get skipped - this causes the wallet to think it has not full processed the blocks, as there is no longer a 'last transaction in block' transaction to be processed.
To my knowledge this has not occurred before, but this will guard against it in case it does.
> Fix block with final transaction with invalid public key preventing syncing

- COMPILE.md
Credit to Lydia Fox for finding the broken link
> Updating SSL links

- .github/workflows/matrix.yml
This reverts commit 686af0ff34213d49f289ba25521283a0cf125a86.
The commit in question linked the windows build against the wrong OpenSSL binaries thus resulting in #1066 as they are not properly linked for windows. This change reverts that change to install the correct openssl development packages with the necessary *.lib files needed by MSVC.
> Revert "openssl is provided by windows image"

- src/walletbackend/WalletSynchronizer.cpp
If you exit after the daemon shut down while trying to fetch global indexes, the program won't exit till the daemon comes back online and it can get the indexes.
> Fix a potential infinite loop while exiting

- COMPILE.md
I have tested these instructions on a fresh VM with ubuntu latest LTS, and they work fine. These seem to be the instructions the CI tests use. The cmake that ships in the default ubuntu repositories is 3.16.3 right now, so needing to install CMake from pip is no longer an issue. I'm thinking the clang instructions could probably be cleaned up significantly as well as they also use the same exact build instructions in the matrix, with the exception of the cc and ccx variables and compilers installed obviously, but I don't use clang so I didn't want to mess with it.
> Update gcc build instructions to match the matrix.yml

- include/ZedwalletTypes.h
- src/walletbackend/WalletBackend.cpp
- src/zedwallet++/Menu.cpp
- src/zedwallet++/ParseArguments.cpp
- src/zedwallet++/ParseArguments.h
Added a an option to reset when starting the wallet with the flag `./zedwallet -w walletName -p password --reset <block height>`
> Zedwallet reset flag

- .github/workflows/matrix.yml
* I don't know what's wrong with installed boost 1.72.0 in github action virtual environment.
* This just should fix Windows build in gha
> Install boot 1.69 instead for Windows gha build

- src/cryptonotecore/Core.cpp
- src/cryptonotecore/Core.h
- src/cryptonotecore/ValidateTransaction.cpp
If a transaction fails validation, bubble the actual reason supplied in the validation routine up to the top so that we can do better troubleshooting later. The message, in some cases, then includes additional information that  may be helpful for further troubleshooting.
> Bubble Up Transaction Validation Details

- include/JsonHelper.h
- src/walletapi/ApiDispatcher.cpp
- src/zedwallet++/CommandImplementations.cpp
* Fixes the `scanHeight` argument being ignored when using the `/reset` call
* Fixes the default rewind height of -1000 blocks not being correctly used
> Fix wallet-api and zedwallet reset/rewind bugs

- src/config/CryptoNoteConfig.h
We've moved CZ server room location to a new place and switched ISP. Hence a new IP address.
> Update CuveeCZ seed node IP address
